# Generated by Django 5.2.10 on 2026-02-03 09:02

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0002_storagezone_storagelocation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Receiving",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="Номер приёмки"
                    ),
                ),
                (
                    "supplier_name",
                    models.CharField(max_length=255, verbose_name="Поставщик"),
                ),
                (
                    "supplier_doc_no",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        verbose_name="Номер документа поставщика",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Черновик"),
                            ("IN_PROGRESS", "В процессе"),
                            ("COMPLETED", "Завершена"),
                            ("CANCELLED", "Отменена"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "expected_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Плановая дата поставки"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата завершения"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receivings_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Приёмка",
                "verbose_name_plural": "Приёмки",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="ReceivingLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "supplier_sku",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        verbose_name="Артикул поставщика/штрихкод",
                    ),
                ),
                (
                    "qty_expected",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Ожидаемо, шт",
                    ),
                ),
                (
                    "qty_received",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Принято, шт",
                    ),
                ),
                (
                    "has_serial_numbers",
                    models.BooleanField(
                        default=False, verbose_name="Есть серийные номера"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receiving_lines",
                        to="catalog.product",
                        verbose_name="Товар",
                    ),
                ),
                (
                    "receiving",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="receiving.receiving",
                        verbose_name="Приёмка",
                    ),
                ),
                (
                    "storage_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receiving_lines",
                        to="catalog.storagelocation",
                        verbose_name="Место хранения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Строка приёмки",
                "verbose_name_plural": "Строки приёмки",
                "ordering": ["receiving_id", "id"],
            },
        ),
        migrations.CreateModel(
            name="ReceivingSerial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(max_length=128, verbose_name="Серийный номер"),
                ),
                (
                    "line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="serials",
                        to="receiving.receivingline",
                        verbose_name="Строка приёмки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Серийный номер приёмки",
                "verbose_name_plural": "Серийные номера приёмки",
                "unique_together": {("line", "serial_number")},
            },
        ),
    ]
