# Generated by Django 5.2.10 on 2026-02-22 18:39

from django.db import migrations, models


def _normalize_code(raw):
    if not raw:
        return ""
    cleaned = "".join(ch for ch in str(raw).upper() if ch.isascii() and ch.isalnum())
    return cleaned[:24]


def _make_unique_code(existing_codes, base_code):
    base = _normalize_code(base_code) or "SUP"
    if base not in existing_codes:
        existing_codes.add(base)
        return base

    idx = 1
    while True:
        candidate = f"{base}{idx:02d}"[:24]
        if candidate not in existing_codes:
            existing_codes.add(candidate)
            return candidate
        idx += 1


def seed_suppliers(apps, schema_editor):
    Supplier = apps.get_model("receiving", "Supplier")
    Receiving = apps.get_model("receiving", "Receiving")

    default_suppliers = [
        ("AUTOTRADE", "ООО АвтоТрейд"),
        ("PARTSCOM", "ООО ПартсКом"),
        ("EFP", "EFP Parts"),
        ("EXIST", "Exist"),
        ("EMEX", "Emex"),
    ]

    existing_codes = set(Supplier.objects.values_list("code", flat=True))

    for code, name in default_suppliers:
        if not Supplier.objects.filter(name=name).exists():
            Supplier.objects.create(
                code=_make_unique_code(existing_codes, code),
                name=name,
                is_active=True,
            )

    existing_names = (
        Receiving.objects.exclude(supplier_name__isnull=True)
        .exclude(supplier_name="")
        .values_list("supplier_name", flat=True)
        .distinct()
    )
    for supplier_name in existing_names:
        if Supplier.objects.filter(name=supplier_name).exists():
            continue
        auto_code = _normalize_code(supplier_name)[:12] or "SUP"
        Supplier.objects.create(
            code=_make_unique_code(existing_codes, auto_code),
            name=supplier_name,
            is_active=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("receiving", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=24, unique=True, verbose_name="Код поставщика"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название поставщика"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "Поставщик",
                "verbose_name_plural": "Поставщики",
                "ordering": ["name"],
            },
        ),
        migrations.RunPython(seed_suppliers, migrations.RunPython.noop),
    ]
