# Generated by ChatGPT on 2026-02-22

from django.db import migrations


def _normalize_ascii_code(raw):
    if not raw:
        return ""
    cleaned = "".join(ch for ch in str(raw).upper() if ch.isascii() and ch.isalnum())
    return cleaned[:24]


def _next_unique(base, used_codes):
    base = _normalize_ascii_code(base) or "SUP"
    if base not in used_codes:
        used_codes.add(base)
        return base

    idx = 1
    while True:
        suffix = f"{idx:02d}"
        candidate = f"{base[:24 - len(suffix)]}{suffix}"
        if candidate not in used_codes:
            used_codes.add(candidate)
            return candidate
        idx += 1


def normalize_supplier_codes(apps, schema_editor):
    Supplier = apps.get_model("receiving", "Supplier")
    used_codes = set()

    for supplier in Supplier.objects.order_by("id"):
        base = _normalize_ascii_code(supplier.code)
        if not base:
            base = _normalize_ascii_code(supplier.name)
        new_code = _next_unique(base, used_codes)
        if supplier.code != new_code:
            supplier.code = new_code
            supplier.save(update_fields=["code"])


class Migration(migrations.Migration):
    dependencies = [
        ("receiving", "0002_supplier"),
    ]

    operations = [
        migrations.RunPython(normalize_supplier_codes, migrations.RunPython.noop),
    ]
