# Generated by Django 5.2.10 on 2026-02-22 19:36

import django.db.models.deletion
from django.db import migrations, models


def backfill_receiving_warehouse(apps, schema_editor):
    Receiving = apps.get_model("receiving", "Receiving")
    ReceivingLine = apps.get_model("receiving", "ReceivingLine")

    receivings = Receiving.objects.filter(warehouse__isnull=True)
    for receiving in receivings.iterator():
        warehouse_ids = set(
            ReceivingLine.objects.filter(
                receiving_id=receiving.id,
                storage_location__isnull=False,
                storage_location__zone__warehouse__isnull=False,
            )
            .values_list("storage_location__zone__warehouse_id", flat=True)
            .distinct()
        )
        if len(warehouse_ids) == 1:
            receiving.warehouse_id = warehouse_ids.pop()
            receiving.save(update_fields=["warehouse"])


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_backorder_tool"),
        ("receiving", "0003_normalize_supplier_codes"),
    ]

    operations = [
        migrations.AddField(
            model_name="receiving",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receivings",
                to="catalog.warehouse",
                verbose_name="Склад",
            ),
        ),
        migrations.RunPython(backfill_receiving_warehouse, migrations.RunPython.noop),
    ]
