# Generated by Django 5.2.10 on 2026-02-07 19:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0003_branch_warehouseaccess_alter_storagezone_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WarehouseLayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "floor_points",
                    models.JSONField(
                        default=list,
                        help_text="Массив точек [[x, z], ...] для построения контура склада",
                        verbose_name="Точки контура пола",
                    ),
                ),
                (
                    "is_layout_defined",
                    models.BooleanField(
                        default=False,
                        help_text="True, если контур склада уже нарисован",
                        verbose_name="Разметка выполнена",
                    ),
                ),
                (
                    "warehouse",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layout",
                        to="catalog.warehouse",
                        verbose_name="Склад",
                    ),
                ),
            ],
            options={
                "verbose_name": "Геометрия склада",
                "verbose_name_plural": "Геометрии складов",
            },
        ),
        migrations.CreateModel(
            name="StorageObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "object_type",
                    models.CharField(
                        choices=[
                            ("RACK", "Стеллаж"),
                            ("SHELF", "Полка"),
                            ("CELL", "Ячейка"),
                            ("FLOOR", "Напольное место"),
                        ],
                        db_index=True,
                        max_length=16,
                        verbose_name="Тип объекта",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Код объекта"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Название"
                    ),
                ),
                (
                    "position_x",
                    models.FloatField(default=0.0, verbose_name="Позиция X"),
                ),
                (
                    "position_z",
                    models.FloatField(default=0.0, verbose_name="Позиция Z"),
                ),
                (
                    "position_y",
                    models.FloatField(default=0.0, verbose_name="Позиция Y (высота)"),
                ),
                (
                    "width",
                    models.FloatField(
                        default=1.0,
                        validators=[django.core.validators.MinValueValidator(0.1)],
                        verbose_name="Ширина",
                    ),
                ),
                (
                    "depth",
                    models.FloatField(
                        default=1.0,
                        validators=[django.core.validators.MinValueValidator(0.1)],
                        verbose_name="Глубина",
                    ),
                ),
                (
                    "height",
                    models.FloatField(
                        default=1.0,
                        validators=[django.core.validators.MinValueValidator(0.1)],
                        verbose_name="Высота",
                    ),
                ),
                (
                    "rotation_y",
                    models.FloatField(
                        default=0.0,
                        help_text="Поворот объекта вокруг вертикальной оси",
                        verbose_name="Поворот вокруг Y (градусы)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storage_objects",
                        to="catalog.warehouse",
                        verbose_name="Склад",
                    ),
                ),
            ],
            options={
                "verbose_name": "Объект хранения",
                "verbose_name_plural": "Объекты хранения",
                "ordering": ["warehouse", "object_type", "code"],
                "indexes": [
                    models.Index(
                        fields=["warehouse", "object_type"],
                        name="idx_storage_obj_wh_type",
                    )
                ],
            },
        ),
    ]
