# Generated by Django 5.2.10 on 2026-02-07 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_branch_warehouseaccess_alter_storagezone_options_and_more"),
        ("warehouse_3d", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="storageobject",
            name="storage_location",
            field=models.ForeignKey(
                blank=True,
                help_text="Связь с логическим местом хранения из каталога",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="storage_objects_3d",
                to="catalog.storagelocation",
                verbose_name="Место хранения",
            ),
        ),
    ]
