# Generated by Django 5.2.10 on 2026-04-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse_3d", "0002_storageobject_storage_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouselayout",
            name="gate_x",
            field=models.FloatField(
                blank=True,
                help_text="Если не задано — берётся середина первой грани контура",
                null=True,
                verbose_name="Координата ворот X",
            ),
        ),
        migrations.AddField(
            model_name="warehouselayout",
            name="gate_z",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Координата ворот Z"
            ),
        ),
    ]
