from __future__ import annotations

import re
from pathlib import Path

from django.core.management import BaseCommand, CommandError
from django.db import connection


class Command(BaseCommand):
    help = "Пересоздаёт db/schema.sql из актуальной PostgreSQL схемы public."

    def add_arguments(self, parser):
        parser.add_argument(
            "--output",
            default="db/schema.sql",
            help="Путь к выходному файлу (по умолчанию db/schema.sql)",
        )

    def handle(self, *args, **options):
        if connection.vendor != "postgresql":
            raise CommandError("Команда поддерживает только PostgreSQL.")

        output_path = Path(options["output"])
        ddl = self._build_schema_ddl()
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(ddl, encoding="utf-8")
        self.stdout.write(self.style.SUCCESS(f"Готово: {output_path.as_posix()}"))

    def _build_schema_ddl(self) -> str:
        lines: list[str] = [
            "-- WMS автозапчастей — PostgreSQL schema (DDL)",
            "-- Этот файл генерируется командой:",
            "--   python manage.py rebuild_schema_sql",
            "-- Источник: фактическая схема БД (schema=public).",
            "",
            "BEGIN;",
            "",
        ]
        fk_constraints: list[tuple[str, str, str]] = []

        for table in self._get_tables():
            lines.extend(self._render_table_block(table, fk_constraints))

        if fk_constraints:
            lines.append("-- =========================")
            lines.append("-- Foreign Keys")
            lines.append("-- =========================")
            lines.append("")
            for table, conname, definition in fk_constraints:
                lines.extend(self._render_fk_do_block(table, conname, definition))

        lines.append("COMMIT;")
        lines.append("")
        return "\n".join(lines)

    def _get_tables(self) -> list[str]:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                SELECT table_name
                FROM information_schema.tables
                WHERE table_schema = 'public'
                  AND table_type = 'BASE TABLE'
                ORDER BY table_name
                """
            )
            return [row[0] for row in cursor.fetchall()]

    def _render_table_block(self, table: str, fk_constraints: list[tuple[str, str, str]]) -> list[str]:
        out: list[str] = [f"-- {table}"]

        columns = self._get_columns(table)
        constraints = self._get_constraints(table)

        constraint_names = {name for name, _ctype, _def in constraints}
        create_lines: list[str] = []

        for column in columns:
            line = f'    {column["name"]} {column["type"]}'
            if column["identity"] == "a":
                line += " GENERATED ALWAYS AS IDENTITY"
            elif column["identity"] == "d":
                line += " GENERATED BY DEFAULT AS IDENTITY"
            elif column["default"] is not None:
                line += f' DEFAULT {column["default"]}'
            if column["not_null"]:
                line += " NOT NULL"
            create_lines.append(line)

        for conname, contype, definition in constraints:
            if contype == "f":
                fk_constraints.append((table, conname, definition))
                continue
            create_lines.append(f"    CONSTRAINT {conname} {definition}")

        out.append(f"CREATE TABLE IF NOT EXISTS {table} (")
        out.append(",\n".join(create_lines))
        out.append(");")
        out.append("")

        for index_name, index_def in self._get_indexes(table):
            if index_name in constraint_names:
                continue
            out.append(f"{self._inject_if_not_exists(index_def)};")

        if out[-1] != "":
            out.append("")

        return out

    def _get_columns(self, table: str) -> list[dict[str, str | bool | None]]:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                SELECT
                    a.attname AS column_name,
                    pg_catalog.format_type(a.atttypid, a.atttypmod) AS data_type,
                    a.attnotnull AS not_null,
                    a.attidentity AS identity_mode,
                    pg_get_expr(ad.adbin, ad.adrelid) AS default_value
                FROM pg_attribute a
                JOIN pg_class cls ON cls.oid = a.attrelid
                JOIN pg_namespace ns ON ns.oid = cls.relnamespace
                LEFT JOIN pg_attrdef ad ON ad.adrelid = a.attrelid AND ad.adnum = a.attnum
                WHERE ns.nspname = 'public'
                  AND cls.relname = %s
                  AND a.attnum > 0
                  AND NOT a.attisdropped
                ORDER BY a.attnum
                """,
                [table],
            )
            rows = cursor.fetchall()
        return [
            {
                "name": row[0],
                "type": row[1],
                "not_null": bool(row[2]),
                "identity": row[3],
                "default": row[4],
            }
            for row in rows
        ]

    def _get_constraints(self, table: str) -> list[tuple[str, str, str]]:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                SELECT conname, contype, pg_get_constraintdef(oid)
                FROM pg_constraint
                WHERE conrelid = %s::regclass
                ORDER BY conname
                """,
                [table],
            )
            return [(row[0], row[1], row[2]) for row in cursor.fetchall()]

    def _get_indexes(self, table: str) -> list[tuple[str, str]]:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                SELECT indexname, indexdef
                FROM pg_indexes
                WHERE schemaname = 'public'
                  AND tablename = %s
                ORDER BY indexname
                """,
                [table],
            )
            return [(row[0], row[1]) for row in cursor.fetchall()]

    def _inject_if_not_exists(self, index_def: str) -> str:
        return re.sub(r"^CREATE( UNIQUE)? INDEX ", r"CREATE\1 INDEX IF NOT EXISTS ", index_def, count=1)

    def _render_fk_do_block(self, table: str, conname: str, definition: str) -> list[str]:
        safe_table = table.replace("'", "''")
        safe_conname = conname.replace("'", "''")
        return [
            "DO $$",
            "BEGIN",
            "    IF NOT EXISTS (",
            "        SELECT 1",
            "        FROM pg_constraint",
            f"        WHERE conname = '{safe_conname}'",
            f"          AND conrelid = '{safe_table}'::regclass",
            "    ) THEN",
            f"        ALTER TABLE {table} ADD CONSTRAINT {conname} {definition};",
            "    END IF;",
            "END $$;",
            "",
        ]
