from django.urls import path

from . import docs
from . import views

urlpatterns = [
    path("openapi.json", docs.openapi_json, name="api_v1_openapi"),
    path("docs/", docs.swagger_ui, name="api_v1_docs"),
    path("redoc/", docs.redoc_ui, name="api_v1_redoc"),
    path("health/", views.health, name="api_v1_health"),
    path("me/", views.me, name="api_v1_me"),
    path("dashboard/summary/", views.dashboard_summary_api, name="api_v1_dashboard_summary"),
    path("manual/", views.manual_api, name="api_v1_manual"),
    path("brands/", views.brands_list, name="api_v1_brands_list"),
    path("categories/", views.categories_list, name="api_v1_categories_list"),
    path("vehicles/makes/", views.vehicle_makes_list, name="api_v1_vehicle_makes_list"),
    path("vehicles/models/", views.vehicle_models_list, name="api_v1_vehicle_models_list"),
    path("warehouses/", views.warehouses_list_api, name="api_v1_warehouses_list"),
    path("warehouses/<int:pk>/map/", views.warehouse_map_api, name="api_v1_warehouse_map"),
    path("warehouses/<int:pk>/objects/", views.warehouse_objects_api, name="api_v1_warehouse_objects"),
    path("products/", views.products_list, name="api_v1_products_list"),
    path("products/<int:pk>/", views.product_detail, name="api_v1_product_detail"),
    path("products/<int:pk>/xrefs/", views.product_xrefs_list, name="api_v1_product_xrefs_list"),
    path("receivings/", views.receivings_list, name="api_v1_receivings_list"),
    path("receivings/<int:pk>/", views.receiving_detail_api, name="api_v1_receiving_detail"),
    path("receivings/<int:pk>/lines/", views.receiving_lines_list_create, name="api_v1_receiving_lines"),
    path("receivings/<int:pk>/scan/", views.receiving_scan, name="api_v1_receiving_scan"),
    path("receivings/<int:pk>/actions/<str:action>/", views.receiving_action, name="api_v1_receiving_action"),
    path("stock/", views.stock_list, name="api_v1_stock_list"),
    path("stock/<int:pk>/analogs/", views.stock_analogs, name="api_v1_stock_analogs"),
    path("inventories/", views.inventories_list, name="api_v1_inventories_list"),
    path("inventories/<int:pk>/", views.inventory_detail_api, name="api_v1_inventory_detail"),
    path("inventories/<int:pk>/lines/", views.inventory_lines_list_create, name="api_v1_inventory_lines"),
    path("inventories/<int:pk>/actions/<str:action>/", views.inventory_action, name="api_v1_inventory_action"),
    path("tasks/", views.tasks_list_create, name="api_v1_tasks"),
    path("tasks/<int:pk>/", views.task_detail_api, name="api_v1_task_detail"),
    path("tasks/<int:pk>/actions/<str:action>/", views.task_action, name="api_v1_task_action"),
    path("tasks/<int:pk>/comments/", views.task_comments_list_create, name="api_v1_task_comments"),
    path("tasks/monitoring/", views.tasks_monitoring_summary, name="api_v1_tasks_monitoring"),
    path("orders/", views.orders_list_create, name="api_v1_orders_list_create"),
    path("orders/<int:pk>/", views.order_detail_update, name="api_v1_order_detail_update"),
    path("orders/<int:pk>/lines/", views.order_lines_list_create, name="api_v1_order_lines_list_create"),
    path("orders/<int:pk>/actions/<str:action>/", views.order_action, name="api_v1_order_action"),
    path("picking-tasks/", views.picking_tasks_list, name="api_v1_picking_tasks_list"),
    path("picking-tasks/<int:pk>/", views.picking_task_detail_api, name="api_v1_picking_task_detail"),
    path("picking-tasks/<int:pk>/lines/", views.picking_task_lines_list_create, name="api_v1_picking_task_lines"),
    path("picking-tasks/<int:pk>/actions/<str:action>/", views.picking_task_action, name="api_v1_picking_task_action"),
    path("reports/abc-xyz/", views.reports_abc_xyz, name="api_v1_reports_abc_xyz"),
    path("reports/dead-stock/", views.reports_dead_stock, name="api_v1_reports_dead_stock"),
    path("reports/analogs-vs-originals/", views.reports_analogs_vs_originals, name="api_v1_reports_analogs_vs_originals"),
    path("reports/picking-errors/", views.reports_picking_errors, name="api_v1_reports_picking_errors"),
    path("reports/demand-forecast/", views.reports_demand_forecast, name="api_v1_reports_demand_forecast"),
    path("reports/staff-efficiency/", views.reports_staff_efficiency, name="api_v1_reports_staff_efficiency"),
]
