# Generated by Django 5.2.10 on 2026-04-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("LOGIN", "Вход в систему"),
                    ("LOGOUT", "Выход из системы"),
                    ("CREATE", "Создание"),
                    ("UPDATE", "Обновление"),
                    ("DELETE", "Удаление"),
                    ("ACTIVATE", "Активация"),
                    ("DEACTIVATE", "Деактивация"),
                    ("BACKUP_CREATE", "Создание резервной копии"),
                    ("BACKUP_RESTORE", "Восстановление из резервной копии"),
                    ("BACKUP_DELETE", "Удаление резервной копии"),
                    ("PASSWORD_RESET", "Сброс пароля"),
                    ("VIEW", "Просмотр"),
                    ("LAYOUT_CREATE", "Создание объекта 3D"),
                    ("LAYOUT_UPDATE", "Изменение объекта 3D"),
                    ("LAYOUT_DELETE", "Удаление объекта 3D"),
                    ("LAYOUT_BULK_CREATE", "Массовое создание объектов 3D"),
                    ("LAYOUT_ROLLBACK", "Откат изменения 3D"),
                ],
                db_index=True,
                max_length=32,
                verbose_name="Действие",
            ),
        ),
    ]
