# Generated by Django 5.2.10 on 2026-02-03 15:30

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0002_storagezone_storagelocation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="Номер инвентаризации"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Черновик"),
                            ("IN_PROGRESS", "В процессе"),
                            ("COMPLETED", "Завершена"),
                            ("CANCELLED", "Отменена"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Начало"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Завершение"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventories_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventories",
                        to="catalog.storagezone",
                        verbose_name="Зона",
                    ),
                ),
            ],
            options={
                "verbose_name": "Инвентаризация",
                "verbose_name_plural": "Инвентаризации",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="InventoryLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qty_book",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="По учёту, шт",
                    ),
                ),
                (
                    "qty_actual",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Фактически, шт",
                    ),
                ),
                (
                    "discrepancy",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Расхождение",
                    ),
                ),
                (
                    "inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="inventory.inventory",
                        verbose_name="Инвентаризация",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_lines",
                        to="catalog.product",
                        verbose_name="Товар",
                    ),
                ),
                (
                    "storage_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_lines",
                        to="catalog.storagelocation",
                        verbose_name="Место хранения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Строка инвентаризации",
                "verbose_name_plural": "Строки инвентаризации",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("inventory", "product", "storage_location"),
                        name="uniq_inv_line_inv_prod_loc",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qty_available",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Доступно, шт",
                    ),
                ),
                (
                    "qty_reserved",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Зарезервировано, шт",
                    ),
                ),
                (
                    "batch_no",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Номер партии"
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Срок годности"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_items",
                        to="catalog.product",
                        verbose_name="Товар",
                    ),
                ),
                (
                    "storage_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_items",
                        to="catalog.storagelocation",
                        verbose_name="Место хранения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Остаток",
                "verbose_name_plural": "Остатки",
                "indexes": [
                    models.Index(fields=["product"], name="idx_stock_product"),
                    models.Index(
                        fields=["storage_location"], name="idx_stock_location"
                    ),
                    models.Index(
                        fields=["qty_available"], name="idx_stock_qty_available"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "storage_location", "batch_no"),
                        name="uniq_stock_product_location_batch",
                    )
                ],
            },
        ),
    ]
