# Generated by Django 5.2.10 on 2026-04-27 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_product_analog_number_normalized_and_more"),
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("RECEIPT", "Поступление"),
                            ("TRANSFER", "Перемещение"),
                            ("WRITE_OFF", "Списание"),
                            ("ISSUE", "Выдача"),
                            ("RETURN", "Возврат"),
                            ("INVENTORY", "Инвентаризация"),
                            ("ADJUSTMENT", "Корректировка"),
                        ],
                        db_index=True,
                        max_length=16,
                        verbose_name="Тип операции",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Черновик"),
                            ("POSTED", "Проведено"),
                            ("CANCELLED", "Отменено"),
                        ],
                        db_index=True,
                        default="POSTED",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Количество"
                    ),
                ),
                (
                    "batch_no",
                    models.CharField(blank=True, max_length=64, verbose_name="Партия"),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Причина"
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "ref_type",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="Тип документа"
                    ),
                ),
                (
                    "ref_id",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="ID документа"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Создано"
                    ),
                ),
                (
                    "from_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements_out",
                        to="catalog.storagelocation",
                        verbose_name="Откуда",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="catalog.product",
                        verbose_name="Товар",
                    ),
                ),
                (
                    "to_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements_in",
                        to="catalog.storagelocation",
                        verbose_name="Куда",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Движение товара",
                "verbose_name_plural": "Журнал движений",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["product", "-created_at"], name="idx_mov_product_date"
                    ),
                    models.Index(
                        fields=["movement_type", "-created_at"],
                        name="idx_mov_type_date",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("quantity", 0), _negated=True),
                        name="movement_qty_nonzero",
                    )
                ],
            },
        ),
    ]
