# Generated by Django 5.2.10 on 2026-02-04 18:49

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0002_storagezone_storagelocation"),
        ("inventory", "0001_initial"),
        ("picking", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ABCXYZAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField(verbose_name="Начало периода")),
                ("period_end", models.DateField(verbose_name="Конец периода")),
                (
                    "total_sales_qty",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Объём продаж, шт",
                    ),
                ),
                (
                    "total_sales_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Сумма продаж, ₽",
                    ),
                ),
                (
                    "abc_class",
                    models.CharField(
                        blank=True,
                        help_text="A, B, C",
                        max_length=1,
                        verbose_name="ABC класс",
                    ),
                ),
                (
                    "xyz_class",
                    models.CharField(
                        blank=True,
                        help_text="X, Y, Z",
                        max_length=1,
                        verbose_name="XYZ класс",
                    ),
                ),
                (
                    "coefficient_variation",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="Коэффициент вариации",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abcxyz_analyses",
                        to="catalog.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "ABC-XYZ анализ",
                "verbose_name_plural": "ABC-XYZ анализы",
                "indexes": [
                    models.Index(
                        fields=["period_start", "period_end"], name="idx_abcxyz_period"
                    ),
                    models.Index(
                        fields=["abc_class", "xyz_class"], name="idx_abcxyz_class"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AnalogVsOriginalReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField(verbose_name="Начало периода")),
                ("period_end", models.DateField(verbose_name="Конец периода")),
                (
                    "original_sales_qty",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Продажи оригинала, шт",
                    ),
                ),
                (
                    "analog_sales_qty",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Продажи аналога, шт",
                    ),
                ),
                (
                    "original_sales_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Сумма продаж оригинала, ₽",
                    ),
                ),
                (
                    "analog_sales_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Сумма продаж аналога, ₽",
                    ),
                ),
                (
                    "substitution_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Процент замен оригиналов на аналоги",
                        max_digits=5,
                        null=True,
                        verbose_name="Коэффициент замещения",
                    ),
                ),
                (
                    "calculated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Рассчитано"),
                ),
                (
                    "analog_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analog_reports_as_analog",
                        to="catalog.product",
                        verbose_name="Аналог",
                    ),
                ),
                (
                    "original_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analog_reports_as_original",
                        to="catalog.product",
                        verbose_name="Оригинальный товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отчёт аналоги vs оригиналы",
                "verbose_name_plural": "Отчёты аналоги vs оригиналы",
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "period_start",
                            "period_end",
                            "original_product",
                            "analog_product",
                        ),
                        name="uniq_analog_report_period_products",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DeadStockReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qty_available",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Количество, шт",
                    ),
                ),
                (
                    "days_without_movement",
                    models.IntegerField(default=0, verbose_name="Дней без движения"),
                ),
                (
                    "last_movement_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Последнее движение"
                    ),
                ),
                (
                    "estimated_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Оценочная стоимость, ₽",
                    ),
                ),
                (
                    "calculated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Рассчитано"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dead_stock_reports",
                        to="catalog.product",
                        verbose_name="Товар",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dead_stock_reports",
                        to="inventory.stock",
                        verbose_name="Остаток",
                    ),
                ),
            ],
            options={
                "verbose_name": "Мёртвый остаток",
                "verbose_name_plural": "Мёртвые остатки",
                "indexes": [
                    models.Index(
                        fields=["days_without_movement"], name="idx_dead_stock_days"
                    ),
                    models.Index(
                        fields=["calculated_at"], name="idx_dead_stock_calculated"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PickingError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "error_type",
                    models.CharField(
                        choices=[
                            ("WRONG_PRODUCT", "Неверный товар"),
                            ("WRONG_QTY", "Неверное количество"),
                            ("WRONG_LOCATION", "Неверное место"),
                            ("DAMAGED", "Повреждённый товар"),
                            ("MISSING", "Товар отсутствует"),
                        ],
                        max_length=32,
                        verbose_name="Тип ошибки",
                    ),
                ),
                (
                    "expected_qty",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Ожидаемое количество",
                    ),
                ),
                (
                    "actual_qty",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Фактическое количество",
                    ),
                ),
                (
                    "detected_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Обнаружено"),
                ),
                (
                    "resolved",
                    models.BooleanField(default=False, verbose_name="Исправлено"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Исправлено"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Примечания")),
                (
                    "actual_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="picking_errors_actual",
                        to="catalog.product",
                        verbose_name="Фактический товар",
                    ),
                ),
                (
                    "detected_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detected_picking_errors",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Обнаружил",
                    ),
                ),
                (
                    "expected_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="picking_errors_expected",
                        to="catalog.product",
                        verbose_name="Ожидаемый товар",
                    ),
                ),
                (
                    "order_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="picking_errors",
                        to="picking.orderline",
                        verbose_name="Строка заказа",
                    ),
                ),
                (
                    "picking_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="errors",
                        to="picking.pickingline",
                        verbose_name="Строка подбора",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_picking_errors",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Исправил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ошибка подбора",
                "verbose_name_plural": "Ошибки подбора",
                "indexes": [
                    models.Index(fields=["error_type"], name="idx_picking_error_type"),
                    models.Index(
                        fields=["detected_at"], name="idx_picking_error_detected"
                    ),
                    models.Index(
                        fields=["resolved"], name="idx_picking_error_resolved"
                    ),
                ],
            },
        ),
    ]
