# Generated by Django 5.2.10 on 2026-02-16 20:49

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_branch_warehouseaccess_alter_storagezone_options_and_more"),
        ("reports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DemandForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("forecast_date", models.DateField(verbose_name="Дата прогноза")),
                (
                    "period_start",
                    models.DateField(verbose_name="Начало периода прогноза"),
                ),
                ("period_end", models.DateField(verbose_name="Конец периода прогноза")),
                (
                    "forecasted_qty",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Прогнозируемое количество, шт",
                    ),
                ),
                (
                    "confidence_level",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="От 0 до 100, процент уверенности в прогнозе",
                        max_digits=5,
                        null=True,
                        verbose_name="Уровень уверенности",
                    ),
                ),
                (
                    "seasonal_factor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Коэффициент сезонности (1.0 = норма, >1.0 = сезон, <1.0 = несезон)",
                        max_digits=5,
                        null=True,
                        verbose_name="Сезонный коэффициент",
                    ),
                ),
                (
                    "trend_factor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Тренд продаж (положительный/отрицательный)",
                        max_digits=5,
                        null=True,
                        verbose_name="Тренд",
                    ),
                ),
                (
                    "historical_sales_qty",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Исторические продажи, шт",
                    ),
                ),
                (
                    "historical_period_start",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Начало исторического периода",
                    ),
                ),
                (
                    "historical_period_end",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Конец исторического периода",
                    ),
                ),
                (
                    "calculated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Рассчитано"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Примечания")),
                (
                    "calculated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calculated_forecasts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Рассчитал",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demand_forecasts",
                        to="catalog.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Прогноз спроса",
                "verbose_name_plural": "Прогнозы спроса",
                "ordering": ["-forecast_date", "product"],
                "indexes": [
                    models.Index(
                        fields=["product", "forecast_date"],
                        name="idx_forecast_product_date",
                    ),
                    models.Index(
                        fields=["period_start", "period_end"],
                        name="idx_forecast_period",
                    ),
                ],
            },
        ),
    ]
