# Generated by Django 5.2.10 on 2026-02-16 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        ("picking", "0001_initial"),
        ("receiving", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("RECEIVING", "Приёмка"),
                            ("INVENTORY", "Инвентаризация"),
                            ("PICKING", "Подбор"),
                            ("SHIPPING", "Отгрузка"),
                            ("STOCK_MOVEMENT", "Перемещение товара"),
                            ("OTHER", "Прочее"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="Тип задачи",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Ожидает"),
                            ("IN_PROGRESS", "В работе"),
                            ("COMPLETED", "Завершена"),
                            ("CANCELLED", "Отменена"),
                            ("ON_HOLD", "Приостановлена"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Низкий"),
                            ("NORMAL", "Обычный"),
                            ("HIGH", "Высокий"),
                            ("URGENT", "Срочный"),
                        ],
                        db_index=True,
                        default="NORMAL",
                        max_length=16,
                        verbose_name="Приоритет",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название задачи"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "due_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Срок выполнения"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Начало"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Завершение"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Метаданные"
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Назначен",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал",
                    ),
                ),
                (
                    "inventory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="inventory.inventory",
                        verbose_name="Инвентаризация",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="picking.order",
                        verbose_name="Заказ",
                    ),
                ),
                (
                    "picking_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="picking.pickingtask",
                        verbose_name="Задача подбора",
                    ),
                ),
                (
                    "receiving",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="receiving.receiving",
                        verbose_name="Приёмка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                ("text", models.TextField(verbose_name="Текст комментария")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="task_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="tasks.task",
                        verbose_name="Задача",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий к задаче",
                "verbose_name_plural": "Комментарии к задачам",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["task_type", "status"], name="idx_task_type_status"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["assigned_to", "status"], name="idx_task_assigned_status"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["priority", "due_date"], name="idx_task_priority_due"
            ),
        ),
    ]
