# Generated by Django 5.2.10 on 2026-02-03 08:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="Код зоны"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=120, verbose_name="Название зоны"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "zone_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="zones",
                        to="catalog.storagezonetype",
                        verbose_name="Тип зоны",
                    ),
                ),
            ],
            options={
                "verbose_name": "Зона хранения",
                "verbose_name_plural": "Зоны хранения",
                "ordering": ["zone_type__sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="StorageLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                ("code", models.CharField(max_length=32, verbose_name="Код места")),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Наименование места"
                    ),
                ),
                (
                    "aisle",
                    models.CharField(blank=True, max_length=16, verbose_name="Ряд"),
                ),
                (
                    "rack",
                    models.CharField(blank=True, max_length=16, verbose_name="Стеллаж"),
                ),
                (
                    "shelf",
                    models.CharField(blank=True, max_length=16, verbose_name="Полка"),
                ),
                (
                    "level",
                    models.CharField(blank=True, max_length=16, verbose_name="Уровень"),
                ),
                (
                    "max_weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Максимальный вес, кг",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="locations",
                        to="catalog.storagezone",
                        verbose_name="Зона",
                    ),
                ),
            ],
            options={
                "verbose_name": "Место хранения",
                "verbose_name_plural": "Места хранения",
                "ordering": ["zone__code", "code"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("zone", "code"), name="uniq_location_zone_code"
                    )
                ],
            },
        ),
    ]
