# Generated by Django 5.2.10 on 2026-02-04 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_storagezone_storagelocation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="Код филиала"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название филиала"),
                ),
                ("address", models.TextField(blank=True, verbose_name="Адрес")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "Филиал",
                "verbose_name_plural": "Филиалы",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="WarehouseAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("VIEW", "Только просмотр"),
                            ("EDIT", "Редактирование"),
                            ("ADMIN", "Администратор"),
                        ],
                        default="VIEW",
                        max_length=16,
                        verbose_name="Уровень доступа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Доступ к складу",
                "verbose_name_plural": "Доступы к складам",
            },
        ),
        migrations.AlterModelOptions(
            name="storagezone",
            options={
                "ordering": ["warehouse__code", "zone_type__sort_order", "code"],
                "verbose_name": "Зона хранения",
                "verbose_name_plural": "Зоны хранения",
            },
        ),
        migrations.AlterField(
            model_name="storagezone",
            name="code",
            field=models.CharField(max_length=32, verbose_name="Код зоны"),
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                ("code", models.CharField(max_length=32, verbose_name="Код склада")),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название склада"),
                ),
                (
                    "width_m",
                    models.DecimalField(
                        decimal_places=2,
                        default=30.0,
                        max_digits=8,
                        verbose_name="Ширина, м",
                    ),
                ),
                (
                    "length_m",
                    models.DecimalField(
                        decimal_places=2,
                        default=40.0,
                        max_digits=8,
                        verbose_name="Длина, м",
                    ),
                ),
                (
                    "height_m",
                    models.DecimalField(
                        decimal_places=2,
                        default=8.0,
                        max_digits=8,
                        verbose_name="Высота, м",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="warehouses",
                        to="catalog.branch",
                        verbose_name="Филиал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Склад",
                "verbose_name_plural": "Склады",
                "ordering": ["branch__code", "code"],
            },
        ),
        migrations.AddField(
            model_name="storagezone",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="zones",
                to="catalog.warehouse",
                verbose_name="Склад",
            ),
        ),
        migrations.AddConstraint(
            model_name="storagezone",
            constraint=models.UniqueConstraint(
                condition=models.Q(("warehouse__isnull", False)),
                fields=("warehouse", "code"),
                name="uniq_zone_warehouse_code",
            ),
        ),
        migrations.AddField(
            model_name="warehouseaccess",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="warehouse_accesses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="warehouseaccess",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accesses",
                to="catalog.warehouse",
                verbose_name="Склад",
            ),
        ),
        migrations.AddConstraint(
            model_name="warehouse",
            constraint=models.UniqueConstraint(
                fields=("branch", "code"), name="uniq_warehouse_branch_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="warehouseaccess",
            constraint=models.UniqueConstraint(
                fields=("user", "warehouse"),
                name="uniq_warehouse_access_user_warehouse",
            ),
        ),
    ]
