# Generated by Django 5.2.10 on 2026-02-16 20:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_branch_warehouseaccess_alter_storagezone_options_and_more"),
        ("picking", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Backorder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "qty_ordered",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Заказано, шт",
                    ),
                ),
                (
                    "qty_fulfilled",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Выполнено, шт",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Ожидает"),
                            ("PARTIAL", "Частично выполнен"),
                            ("FULFILLED", "Выполнен"),
                            ("CANCELLED", "Отменён"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "expected_arrival_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ожидаемая дата поступления"
                    ),
                ),
                (
                    "fulfilled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Выполнено"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Примечания")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_backorders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backorders",
                        to="picking.order",
                        verbose_name="Заказ",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="backorders",
                        to="catalog.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отложенный заказ",
                "verbose_name_plural": "Отложенные заказы",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status"], name="idx_backorder_status"),
                    models.Index(
                        fields=["expected_arrival_date"], name="idx_backorder_arrival"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "tool_type",
                    models.CharField(
                        choices=[
                            ("FORKLIFT", "Штабелёр"),
                            ("HAND_TRUCK", "Ручная тележка"),
                            ("SCANNER", "Сканер штрихкодов"),
                            ("PRINTER", "Принтер этикеток"),
                            ("OTHER", "Прочее"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="Тип инструмента",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="Код/Инвентарный номер"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "brand",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Бренд/Производитель"
                    ),
                ),
                (
                    "model",
                    models.CharField(blank=True, max_length=120, verbose_name="Модель"),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="Доступен"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "checked_out_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Выдан"),
                ),
                (
                    "expected_return_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ожидаемое возвращение"
                    ),
                ),
                (
                    "last_maintenance_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Последнее ТО"
                    ),
                ),
                (
                    "next_maintenance_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Следующее ТО"
                    ),
                ),
                (
                    "maintenance_notes",
                    models.TextField(blank=True, verbose_name="Примечания по ТО"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Примечания")),
                (
                    "current_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tools_in_use",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Текущий пользователь",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tools",
                        to="catalog.warehouse",
                        verbose_name="Склад",
                    ),
                ),
            ],
            options={
                "verbose_name": "Инструмент",
                "verbose_name_plural": "Инструменты",
                "ordering": ["warehouse", "tool_type", "code"],
                "indexes": [
                    models.Index(
                        fields=["warehouse", "is_available"],
                        name="idx_tool_warehouse_available",
                    ),
                    models.Index(fields=["tool_type"], name="idx_tool_type"),
                ],
            },
        ),
    ]
