# Generated by ChatGPT on 2026-02-22

from django.db import migrations


VEHICLE_CATALOG = {
    "Acura": ["MDX", "RDX", "TLX", "ILX", "NSX"],
    "Alfa Romeo": ["Giulia", "Stelvio", "Tonale", "159", "147"],
    "Audi": ["A3", "A4", "A6", "Q3", "Q5", "Q7"],
    "BMW": ["1 Series", "3 Series", "5 Series", "7 Series", "X3", "X5"],
    "BYD": ["Atto 3", "Han", "Tang", "Song", "Dolphin"],
    "Cadillac": ["CT4", "CT5", "XT4", "XT5", "Escalade"],
    "Chery": ["Tiggo 4", "Tiggo 7", "Tiggo 8", "Arrizo 5", "Arrizo 8"],
    "Chevrolet": ["Aveo", "Cruze", "Malibu", "Captiva", "Tahoe"],
    "Chrysler": ["300", "Pacifica", "Voyager", "Sebring", "PT Cruiser"],
    "Citroen": ["C3", "C4", "C5", "Berlingo", "Jumpy"],
    "Daewoo": ["Matiz", "Nexia", "Lanos", "Leganza", "Espero"],
    "Dodge": ["Charger", "Challenger", "Durango", "Journey", "RAM 1500"],
    "Fiat": ["500", "Tipo", "Punto", "Doblo", "Ducato"],
    "Ford": ["Focus", "Mondeo", "Fusion", "Kuga", "Explorer", "Transit"],
    "Geely": ["Coolray", "Atlas", "Emgrand", "Monjaro", "Tugella"],
    "Genesis": ["G70", "G80", "G90", "GV70", "GV80"],
    "GMC": ["Terrain", "Acadia", "Yukon", "Sierra", "Canyon"],
    "Great Wall": ["Poer", "Wingle 7", "Hover H5", "Hover H6", "Deer"],
    "Haval": ["Jolion", "F7", "F7x", "H5", "H9", "Dargo"],
    "Honda": ["Civic", "Accord", "CR-V", "HR-V", "Pilot", "Fit"],
    "Hyundai": ["Solaris", "Elantra", "Sonata", "Tucson", "Santa Fe", "Creta"],
    "Infiniti": ["Q50", "Q60", "QX50", "QX60", "QX80"],
    "Jaguar": ["XE", "XF", "XJ", "F-Pace", "E-Pace"],
    "Jeep": ["Renegade", "Compass", "Cherokee", "Grand Cherokee", "Wrangler"],
    "Kia": ["Rio", "Ceed", "Cerato", "Sportage", "Sorento", "K5"],
    "LADA": ["Granta", "Vesta", "Largus", "Niva Legend", "Niva Travel"],
    "Land Rover": ["Discovery Sport", "Discovery", "Range Rover Evoque", "Range Rover Sport", "Defender"],
    "Lexus": ["IS", "ES", "GS", "RX", "NX", "LX"],
    "Mazda": ["Mazda 2", "Mazda 3", "Mazda 6", "CX-3", "CX-5", "CX-9"],
    "Mercedes": ["A-Class", "C-Class", "E-Class", "S-Class", "GLC", "GLE"],
    "MINI": ["Cooper", "Clubman", "Countryman", "Paceman", "Roadster"],
    "Mitsubishi": ["Lancer", "ASX", "Outlander", "Pajero", "L200"],
    "Nissan": ["Almera", "Sentra", "Teana", "Qashqai", "X-Trail", "Patrol"],
    "Opel": ["Astra", "Insignia", "Corsa", "Mokka", "Zafira"],
    "Peugeot": ["208", "308", "408", "3008", "5008", "Partner"],
    "Porsche": ["911", "Panamera", "Macan", "Cayenne", "Taycan"],
    "Renault": ["Logan", "Sandero", "Duster", "Kaptur", "Megane", "Arkana"],
    "Skoda": ["Fabia", "Octavia", "Superb", "Kodiaq", "Karoq", "Rapid"],
    "Subaru": ["Impreza", "Legacy", "Forester", "Outback", "XV"],
    "Suzuki": ["Swift", "SX4", "Vitara", "Jimny", "Baleno"],
    "Tesla": ["Model 3", "Model S", "Model X", "Model Y", "Cybertruck"],
    "Toyota": ["Corolla", "Camry", "Avensis", "RAV4", "Land Cruiser", "Hilux"],
    "UAZ": ["Patriot", "Hunter", "Pickup", "Bukhanka", "Profi"],
    "Volkswagen": ["Polo", "Golf", "Passat", "Tiguan", "Touareg", "Transporter"],
    "Volvo": ["S60", "S90", "V60", "XC40", "XC60", "XC90"],
}


def seed_vehicle_catalog(apps, schema_editor):
    VehicleMake = apps.get_model("catalog", "VehicleMake")
    VehicleModel = apps.get_model("catalog", "VehicleModel")

    for make_name, model_names in VEHICLE_CATALOG.items():
        make, _ = VehicleMake.objects.get_or_create(name=make_name)
        for model_name in model_names:
            VehicleModel.objects.get_or_create(make=make, name=model_name)


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_backorder_tool"),
    ]

    operations = [
        migrations.RunPython(seed_vehicle_catalog, migrations.RunPython.noop),
    ]
