# Generated by Django 5.2.10 on 2026-02-22 20:19

import re
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


_NON_ALNUM_RE = re.compile(r"[^0-9A-Z]+")


def _normalize(value: str) -> str:
    raw = (value or "").strip().upper()
    return _NON_ALNUM_RE.sub("", raw) if raw else ""


def backfill_product_normalized_fields(apps, schema_editor):
    Product = apps.get_model("catalog", "Product")
    for product in Product.objects.all().only("id", "oem_number", "analog_number").iterator(chunk_size=500):
        Product.objects.filter(pk=product.pk).update(
            oem_number_normalized=_normalize(product.oem_number),
            analog_number_normalized=_normalize(product.analog_number),
        )


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_seed_vehicle_catalog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="analog_number_normalized",
            field=models.CharField(
                blank=True, db_index=True, default="", editable=False, max_length=64
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="oem_number_normalized",
            field=models.CharField(
                blank=True, db_index=True, default="", editable=False, max_length=64
            ),
        ),
        migrations.CreateModel(
            name="ProductChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("CREATE", "Создание"), ("UPDATE", "Изменение")],
                        db_index=True,
                        max_length=16,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="ui", max_length=32, verbose_name="Источник"
                    ),
                ),
                (
                    "changed_fields",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Изменения"
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Комментарий"
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_change_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_logs",
                        to="catalog.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Журнал изменения товара",
                "verbose_name_plural": "Журнал изменений товаров",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["product", "created_at"],
                        name="idx_prod_chlog_product_created",
                    ),
                    models.Index(
                        fields=["action", "created_at"],
                        name="idx_prod_chlog_action_created",
                    ),
                ],
            },
        ),
        migrations.RunPython(backfill_product_normalized_fields, migrations.RunPython.noop),
    ]
