# Generated by Django 5.2.10 on 2026-04-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_product_analog_number_normalized_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="barcode",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="EAN-13 / UPC / любой буквенно-цифровой код. Если пусто — используется внутренний артикул.",
                max_length=64,
                verbose_name="Штрихкод",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["barcode"], name="idx_product_barcode"),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                condition=models.Q(("barcode", ""), _negated=True),
                fields=("barcode",),
                name="uniq_product_barcode_nonempty",
            ),
        ),
    ]
