# Generated by Django 5.2.10 on 2026-02-03 16:35

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0002_storagezone_storagelocation"),
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "number",
                    models.CharField(
                        db_index=True,
                        max_length=32,
                        unique=True,
                        verbose_name="Номер заказа",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=255, verbose_name="Клиент"),
                ),
                (
                    "customer_phone",
                    models.CharField(blank=True, max_length=32, verbose_name="Телефон"),
                ),
                (
                    "customer_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Черновик"),
                            ("CONFIRMED", "Подтверждён"),
                            ("IN_PICKING", "В подборе"),
                            ("PICKED", "Подобран"),
                            ("RESERVED", "Зарезервирован"),
                            ("SHIPPED", "Отгружен"),
                            ("CANCELLED", "Отменён"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="MANUAL",
                        help_text="MANUAL, POS, ONLINE, API",
                        max_length=32,
                        verbose_name="Источник",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="ID из внешней системы",
                        max_length=64,
                        verbose_name="Внешний ID",
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Подтверждён"
                    ),
                ),
                (
                    "picked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Подобран"
                    ),
                ),
                (
                    "shipped_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Отгружен"
                    ),
                ),
                (
                    "reserved_at_window",
                    models.BooleanField(
                        default=False, verbose_name="Зарезервирован у окна"
                    ),
                ),
                (
                    "window_number",
                    models.CharField(
                        blank=True, max_length=16, verbose_name="Номер окна выдачи"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал",
                    ),
                ),
                (
                    "picked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders_picked",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Подобрал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="OrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qty_ordered",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Заказано, шт",
                    ),
                ),
                (
                    "qty_picked",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Подобрано, шт",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Цена",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="picking.order",
                        verbose_name="Заказ",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_lines",
                        to="catalog.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Строка заказа",
                "verbose_name_plural": "Строки заказа",
                "ordering": ["product__name"],
            },
        ),
        migrations.CreateModel(
            name="PickingTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Ожидает"),
                            ("IN_PROGRESS", "В работе"),
                            ("COMPLETED", "Завершена"),
                            ("CANCELLED", "Отменена"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "zone_type_code",
                    models.CharField(
                        help_text="CELL, SHELF, FLOOR — для маршрутизации",
                        max_length=32,
                        verbose_name="Тип зоны",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Начало"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Завершение"
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="picking_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Назначен",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="picking_tasks",
                        to="picking.order",
                        verbose_name="Заказ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача подбора",
                "verbose_name_plural": "Задачи подбора",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="PickingLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qty_picked",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Подобрано, шт",
                    ),
                ),
                (
                    "scanned_oem",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Отсканированный OEM"
                    ),
                ),
                (
                    "order_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="picking_lines",
                        to="picking.orderline",
                        verbose_name="Строка заказа",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="picking_lines",
                        to="inventory.stock",
                        verbose_name="Остаток",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="picking.pickingtask",
                        verbose_name="Задача подбора",
                    ),
                ),
            ],
            options={
                "verbose_name": "Строка подбора",
                "verbose_name_plural": "Строки подбора",
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["status"], name="idx_order_status"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["number"], name="idx_order_number"),
        ),
        migrations.AddConstraint(
            model_name="orderline",
            constraint=models.UniqueConstraint(
                fields=("order", "product"), name="uniq_order_line_order_product"
            ),
        ),
        migrations.AddIndex(
            model_name="pickingtask",
            index=models.Index(fields=["status"], name="idx_picking_task_status"),
        ),
        migrations.AddIndex(
            model_name="pickingtask",
            index=models.Index(fields=["zone_type_code"], name="idx_picking_task_zone"),
        ),
        migrations.AddConstraint(
            model_name="pickingline",
            constraint=models.UniqueConstraint(
                fields=("task", "order_line", "stock"),
                name="uniq_picking_line_task_order_stock",
            ),
        ),
    ]
