

CREATE TABLE IF NOT EXISTS accounts_user (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    role character varying(32) NOT NULL,
    CONSTRAINT accounts_user_pkey PRIMARY KEY (id),
    CONSTRAINT accounts_user_username_key UNIQUE (username)
);

CREATE INDEX IF NOT EXISTS accounts_user_role_57e97df0 ON public.accounts_user USING btree (role);
CREATE INDEX IF NOT EXISTS accounts_user_role_57e97df0_like ON public.accounts_user USING btree (role varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS accounts_user_username_6088629e_like ON public.accounts_user USING btree (username varchar_pattern_ops);

CREATE TABLE IF NOT EXISTS accounts_user_branches (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id bigint NOT NULL,
    branch_id bigint NOT NULL,
    CONSTRAINT accounts_user_branches_pkey PRIMARY KEY (id),
    CONSTRAINT accounts_user_branches_user_id_branch_id_1d77b88a_uniq UNIQUE (user_id, branch_id)
);

CREATE INDEX IF NOT EXISTS accounts_user_branches_branch_id_e134a618 ON public.accounts_user_branches USING btree (branch_id);
CREATE INDEX IF NOT EXISTS accounts_user_branches_user_id_e71cebef ON public.accounts_user_branches USING btree (user_id);

CREATE TABLE IF NOT EXISTS accounts_user_groups (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL,
    CONSTRAINT accounts_user_groups_pkey PRIMARY KEY (id),
    CONSTRAINT accounts_user_groups_user_id_group_id_59c0b32f_uniq UNIQUE (user_id, group_id)
);

CREATE INDEX IF NOT EXISTS accounts_user_groups_group_id_bd11a704 ON public.accounts_user_groups USING btree (group_id);
CREATE INDEX IF NOT EXISTS accounts_user_groups_user_id_52b62117 ON public.accounts_user_groups USING btree (user_id);


CREATE TABLE IF NOT EXISTS accounts_user_user_permissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq UNIQUE (user_id, permission_id),
    CONSTRAINT accounts_user_user_permissions_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS accounts_user_user_permissions_permission_id_113bb443 ON public.accounts_user_user_permissions USING btree (permission_id);
CREATE INDEX IF NOT EXISTS accounts_user_user_permissions_user_id_e4f0a161 ON public.accounts_user_user_permissions USING btree (user_id);

CREATE TABLE IF NOT EXISTS api_apitoken (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name character varying(120) NOT NULL,
    token character varying(64) NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    last_used_at timestamp with time zone,
    user_id bigint NOT NULL,
    CONSTRAINT api_apitoken_pkey PRIMARY KEY (id),
    CONSTRAINT api_apitoken_token_key UNIQUE (token)
);

CREATE INDEX IF NOT EXISTS api_apitoken_is_active_038cd218 ON public.api_apitoken USING btree (is_active);
CREATE INDEX IF NOT EXISTS api_apitoken_token_5c379f84_like ON public.api_apitoken USING btree (token varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS api_apitoken_user_id_9cffaf33 ON public.api_apitoken USING btree (user_id);

CREATE TABLE IF NOT EXISTS auth_group (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name character varying(150) NOT NULL,
    CONSTRAINT auth_group_name_key UNIQUE (name),
    CONSTRAINT auth_group_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);

CREATE TABLE IF NOT EXISTS auth_group_permissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id),
    CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);
CREATE INDEX IF NOT EXISTS auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);

CREATE TABLE IF NOT EXISTS auth_permission (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL,
    CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename),
    CONSTRAINT auth_permission_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);

CREATE TABLE IF NOT EXISTS catalog_backorder (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    qty_ordered numeric(10,2) NOT NULL,
    qty_fulfilled numeric(10,2) NOT NULL,
    status character varying(16) NOT NULL,
    expected_arrival_date date,
    fulfilled_at timestamp with time zone,
    notes text NOT NULL,
    created_by_id bigint NOT NULL,
    order_id bigint NOT NULL,
    product_id bigint NOT NULL,
    CONSTRAINT catalog_backorder_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS catalog_backorder_created_by_id_de961824 ON public.catalog_backorder USING btree (created_by_id);
CREATE INDEX IF NOT EXISTS catalog_backorder_order_id_e77969b3 ON public.catalog_backorder USING btree (order_id);
CREATE INDEX IF NOT EXISTS catalog_backorder_product_id_0651fc0b ON public.catalog_backorder USING btree (product_id);
CREATE INDEX IF NOT EXISTS catalog_backorder_status_d3be7bfb ON public.catalog_backorder USING btree (status);
CREATE INDEX IF NOT EXISTS catalog_backorder_status_d3be7bfb_like ON public.catalog_backorder USING btree (status varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS idx_backorder_arrival ON public.catalog_backorder USING btree (expected_arrival_date);
CREATE INDEX IF NOT EXISTS idx_backorder_status ON public.catalog_backorder USING btree (status);

CREATE TABLE IF NOT EXISTS catalog_branch (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    code character varying(32) NOT NULL,
    name character varying(255) NOT NULL,
    address text NOT NULL,
    is_active boolean NOT NULL,
    CONSTRAINT catalog_branch_code_key UNIQUE (code),
    CONSTRAINT catalog_branch_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS catalog_branch_code_584e00eb_like ON public.catalog_branch USING btree (code varchar_pattern_ops);

CREATE TABLE IF NOT EXISTS catalog_brand (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    name character varying(120) NOT NULL,
    CONSTRAINT catalog_brand_name_key UNIQUE (name),
    CONSTRAINT catalog_brand_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS catalog_brand_name_ea62c47f_like ON public.catalog_brand USING btree (name varchar_pattern_ops);

CREATE TABLE IF NOT EXISTS catalog_category (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    name character varying(120) NOT NULL,
    parent_id bigint,
    CONSTRAINT catalog_category_name_key UNIQUE (name),
    CONSTRAINT catalog_category_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS catalog_category_name_fdc3466c_like ON public.catalog_category USING btree (name varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS catalog_category_parent_id_f61bd017 ON public.catalog_category USING btree (parent_id);

CREATE TABLE IF NOT EXISTS catalog_product (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    internal_sku character varying(64) NOT NULL,
    name character varying(255) NOT NULL,
    oem_number character varying(64) NOT NULL,
    analog_number character varying(64) NOT NULL,
    weight_kg numeric(10,3),
    length_cm numeric(10,2),
    width_cm numeric(10,2),
    height_cm numeric(10,2),
    packaging_type character varying(16) NOT NULL,
    photo character varying(100),
    brand_id bigint NOT NULL,
    category_id bigint NOT NULL,
    analog_number_normalized character varying(64) NOT NULL,
    oem_number_normalized character varying(64) NOT NULL,
    CONSTRAINT catalog_product_internal_sku_key UNIQUE (internal_sku),
    CONSTRAINT catalog_product_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS catalog_product_analog_number_4f5f2cd0 ON public.catalog_product USING btree (analog_number);
CREATE INDEX IF NOT EXISTS catalog_product_analog_number_4f5f2cd0_like ON public.catalog_product USING btree (analog_number varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS catalog_product_analog_number_normalized_b011ae6e ON public.catalog_product USING btree (analog_number_normalized);
CREATE INDEX IF NOT EXISTS catalog_product_analog_number_normalized_b011ae6e_like ON public.catalog_product USING btree (analog_number_normalized varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS catalog_product_brand_id_bb0c7890 ON public.catalog_product USING btree (brand_id);
CREATE INDEX IF NOT EXISTS catalog_product_category_id_35bf920b ON public.catalog_product USING btree (category_id);
CREATE INDEX IF NOT EXISTS catalog_product_internal_sku_a06cf920_like ON public.catalog_product USING btree (internal_sku varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS catalog_product_oem_number_7ff1f00f ON public.catalog_product USING btree (oem_number);
CREATE INDEX IF NOT EXISTS catalog_product_oem_number_7ff1f00f_like ON public.catalog_product USING btree (oem_number varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS catalog_product_oem_number_normalized_a9af852a ON public.catalog_product USING btree (oem_number_normalized);
CREATE INDEX IF NOT EXISTS catalog_product_oem_number_normalized_a9af852a_like ON public.catalog_product USING btree (oem_number_normalized varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS catalog_product_packaging_type_bb79d9c2 ON public.catalog_product USING btree (packaging_type);
CREATE INDEX IF NOT EXISTS catalog_product_packaging_type_bb79d9c2_like ON public.catalog_product USING btree (packaging_type varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS idx_product_analog ON public.catalog_product USING btree (analog_number);
CREATE INDEX IF NOT EXISTS idx_product_brand_cat ON public.catalog_product USING btree (brand_id, category_id);
CREATE INDEX IF NOT EXISTS idx_product_oem ON public.catalog_product USING btree (oem_number);

CREATE TABLE IF NOT EXISTS catalog_productapplicability (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    product_id bigint NOT NULL,
    vehicle_model_id bigint NOT NULL,
    CONSTRAINT catalog_productapplicability_pkey PRIMARY KEY (id),
    CONSTRAINT uniq_product_vehicle_model UNIQUE (product_id, vehicle_model_id)
);

CREATE INDEX IF NOT EXISTS catalog_productapplicability_product_id_904e4c0a ON public.catalog_productapplicability USING btree (product_id);
CREATE INDEX IF NOT EXISTS catalog_productapplicability_vehicle_model_id_3508c865 ON public.catalog_productapplicability USING btree (vehicle_model_id);

CREATE TABLE IF NOT EXISTS catalog_productchangelog (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    action character varying(16) NOT NULL,
    source character varying(32) NOT NULL,
    changed_fields jsonb NOT NULL,
    note character varying(255) NOT NULL,
    changed_by_id bigint,
    product_id bigint NOT NULL,
    CONSTRAINT catalog_productchangelog_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS catalog_productchangelog_action_82d98f56 ON public.catalog_productchangelog USING btree (action);
CREATE INDEX IF NOT EXISTS catalog_productchangelog_action_82d98f56_like ON public.catalog_productchangelog USING btree (action varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS catalog_productchangelog_changed_by_id_80a96c42 ON public.catalog_productchangelog USING btree (changed_by_id);
CREATE INDEX IF NOT EXISTS catalog_productchangelog_product_id_d1bf08a9 ON public.catalog_productchangelog USING btree (product_id);
CREATE INDEX IF NOT EXISTS idx_prod_chlog_action_created ON public.catalog_productchangelog USING btree (action, created_at);
CREATE INDEX IF NOT EXISTS idx_prod_chlog_product_created ON public.catalog_productchangelog USING btree (product_id, created_at);

CREATE TABLE IF NOT EXISTS catalog_productcrossreference (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    relation_type character varying(16) NOT NULL,
    note character varying(255) NOT NULL,
    from_product_id bigint NOT NULL,
    to_product_id bigint NOT NULL,
    CONSTRAINT catalog_productcrossreference_pkey PRIMARY KEY (id),
    CONSTRAINT chk_xref_not_self CHECK ((NOT (from_product_id = to_product_id))),
    CONSTRAINT uniq_xref_from_to_type UNIQUE (from_product_id, to_product_id, relation_type)
);

CREATE INDEX IF NOT EXISTS catalog_productcrossreference_from_product_id_aac20dd5 ON public.catalog_productcrossreference USING btree (from_product_id);
CREATE INDEX IF NOT EXISTS catalog_productcrossreference_relation_type_dc8c819e ON public.catalog_productcrossreference USING btree (relation_type);
CREATE INDEX IF NOT EXISTS catalog_productcrossreference_relation_type_dc8c819e_like ON public.catalog_productcrossreference USING btree (relation_type varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS catalog_productcrossreference_to_product_id_7622d235 ON public.catalog_productcrossreference USING btree (to_product_id);
CREATE INDEX IF NOT EXISTS idx_xref_from_type ON public.catalog_productcrossreference USING btree (from_product_id, relation_type);

CREATE TABLE IF NOT EXISTS catalog_storagelocation (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    code character varying(32) NOT NULL,
    name character varying(120) NOT NULL,
    aisle character varying(16) NOT NULL,
    rack character varying(16) NOT NULL,
    shelf character varying(16) NOT NULL,
    level character varying(16) NOT NULL,
    max_weight_kg numeric(10,3),
    zone_id bigint NOT NULL,
    CONSTRAINT catalog_storagelocation_pkey PRIMARY KEY (id),
    CONSTRAINT uniq_location_zone_code UNIQUE (zone_id, code)
);

CREATE INDEX IF NOT EXISTS catalog_storagelocation_zone_id_2fb24172 ON public.catalog_storagelocation USING btree (zone_id);

CREATE TABLE IF NOT EXISTS catalog_storagezone (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    code character varying(32) NOT NULL,
    name character varying(120) NOT NULL,
    description text NOT NULL,
    zone_type_id bigint NOT NULL,
    warehouse_id bigint,
    CONSTRAINT catalog_storagezone_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS catalog_storagezone_warehouse_id_685b5c9b ON public.catalog_storagezone USING btree (warehouse_id);
CREATE INDEX IF NOT EXISTS catalog_storagezone_zone_type_id_a4eb2043 ON public.catalog_storagezone USING btree (zone_type_id);
CREATE UNIQUE INDEX IF NOT EXISTS uniq_zone_warehouse_code ON public.catalog_storagezone USING btree (warehouse_id, code) WHERE (warehouse_id IS NOT NULL);

CREATE TABLE IF NOT EXISTS catalog_storagezonetype (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    code character varying(32) NOT NULL,
    name character varying(120) NOT NULL,
    description text NOT NULL,
    sort_order integer NOT NULL,
    CONSTRAINT catalog_storagezonetype_code_key UNIQUE (code),
    CONSTRAINT catalog_storagezonetype_pkey PRIMARY KEY (id),
    CONSTRAINT catalog_storagezonetype_sort_order_check CHECK ((sort_order >= 0))
);

CREATE INDEX IF NOT EXISTS catalog_storagezonetype_code_745f12bb_like ON public.catalog_storagezonetype USING btree (code varchar_pattern_ops);

CREATE TABLE IF NOT EXISTS catalog_tool (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    tool_type character varying(32) NOT NULL,
    code character varying(64) NOT NULL,
    name character varying(255) NOT NULL,
    brand character varying(120) NOT NULL,
    model character varying(120) NOT NULL,
    is_available boolean NOT NULL,
    is_active boolean NOT NULL,
    checked_out_at timestamp with time zone,
    expected_return_at timestamp with time zone,
    last_maintenance_date date,
    next_maintenance_date date,
    maintenance_notes text NOT NULL,
    notes text NOT NULL,
    current_user_id bigint,
    warehouse_id bigint,
    CONSTRAINT catalog_tool_code_key UNIQUE (code),
    CONSTRAINT catalog_tool_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS catalog_tool_code_5ef076de_like ON public.catalog_tool USING btree (code varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS catalog_tool_current_user_id_4aab9a88 ON public.catalog_tool USING btree (current_user_id);
CREATE INDEX IF NOT EXISTS catalog_tool_tool_type_259092a4 ON public.catalog_tool USING btree (tool_type);
CREATE INDEX IF NOT EXISTS catalog_tool_tool_type_259092a4_like ON public.catalog_tool USING btree (tool_type varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS catalog_tool_warehouse_id_225ed9dc ON public.catalog_tool USING btree (warehouse_id);
CREATE INDEX IF NOT EXISTS idx_tool_type ON public.catalog_tool USING btree (tool_type);
CREATE INDEX IF NOT EXISTS idx_tool_warehouse_available ON public.catalog_tool USING btree (warehouse_id, is_available);

CREATE TABLE IF NOT EXISTS catalog_vehiclemake (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    name character varying(120) NOT NULL,
    CONSTRAINT catalog_vehiclemake_name_key UNIQUE (name),
    CONSTRAINT catalog_vehiclemake_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS catalog_vehiclemake_name_a0a64e99_like ON public.catalog_vehiclemake USING btree (name varchar_pattern_ops);

CREATE TABLE IF NOT EXISTS catalog_vehiclemodel (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    name character varying(120) NOT NULL,
    make_id bigint NOT NULL,
    CONSTRAINT catalog_vehiclemodel_pkey PRIMARY KEY (id),
    CONSTRAINT uniq_vehicle_model_make_name UNIQUE (make_id, name)
);

CREATE INDEX IF NOT EXISTS catalog_vehiclemodel_make_id_15410b4c ON public.catalog_vehiclemodel USING btree (make_id);

CREATE TABLE IF NOT EXISTS catalog_warehouse (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    code character varying(32) NOT NULL,
    name character varying(255) NOT NULL,
    width_m numeric(8,2) NOT NULL,
    length_m numeric(8,2) NOT NULL,
    height_m numeric(8,2) NOT NULL,
    is_active boolean NOT NULL,
    branch_id bigint NOT NULL,
    CONSTRAINT catalog_warehouse_pkey PRIMARY KEY (id),
    CONSTRAINT uniq_warehouse_branch_code UNIQUE (branch_id, code)
);

CREATE INDEX IF NOT EXISTS catalog_warehouse_branch_id_f77b3dbb ON public.catalog_warehouse USING btree (branch_id);

CREATE TABLE IF NOT EXISTS catalog_warehouseaccess (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    access_level character varying(16) NOT NULL,
    user_id bigint NOT NULL,
    warehouse_id bigint NOT NULL,
    CONSTRAINT catalog_warehouseaccess_pkey PRIMARY KEY (id),
    CONSTRAINT uniq_warehouse_access_user_warehouse UNIQUE (user_id, warehouse_id)
);

CREATE INDEX IF NOT EXISTS catalog_warehouseaccess_user_id_06bf8444 ON public.catalog_warehouseaccess USING btree (user_id);
CREATE INDEX IF NOT EXISTS catalog_warehouseaccess_warehouse_id_9966fc4b ON public.catalog_warehouseaccess USING btree (warehouse_id);

CREATE TABLE IF NOT EXISTS django_admin_log (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0)),
    CONSTRAINT django_admin_log_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);
CREATE INDEX IF NOT EXISTS django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);

CREATE TABLE IF NOT EXISTS django_content_type (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL,
    CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model),
    CONSTRAINT django_content_type_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS django_migrations (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL,
    CONSTRAINT django_migrations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL,
    CONSTRAINT django_session_pkey PRIMARY KEY (session_key)
);

CREATE INDEX IF NOT EXISTS django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);
CREATE INDEX IF NOT EXISTS django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);

CREATE TABLE IF NOT EXISTS inventory_inventory (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    number character varying(32) NOT NULL,
    status character varying(16) NOT NULL,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    created_by_id bigint NOT NULL,
    zone_id bigint,
    CONSTRAINT inventory_inventory_number_key UNIQUE (number),
    CONSTRAINT inventory_inventory_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS inventory_inventory_created_by_id_6b45551c ON public.inventory_inventory USING btree (created_by_id);
CREATE INDEX IF NOT EXISTS inventory_inventory_number_8a7c3f92_like ON public.inventory_inventory USING btree (number varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS inventory_inventory_status_035c54cd ON public.inventory_inventory USING btree (status);
CREATE INDEX IF NOT EXISTS inventory_inventory_status_035c54cd_like ON public.inventory_inventory USING btree (status varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS inventory_inventory_zone_id_f9ac22ee ON public.inventory_inventory USING btree (zone_id);

CREATE TABLE IF NOT EXISTS inventory_inventoryline (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    qty_book numeric(10,2) NOT NULL,
    qty_actual numeric(10,2),
    discrepancy numeric(10,2) NOT NULL,
    inventory_id bigint NOT NULL,
    product_id bigint NOT NULL,
    storage_location_id bigint NOT NULL,
    CONSTRAINT inventory_inventoryline_pkey PRIMARY KEY (id),
    CONSTRAINT uniq_inv_line_inv_prod_loc UNIQUE (inventory_id, product_id, storage_location_id)
);

CREATE INDEX IF NOT EXISTS inventory_inventoryline_inventory_id_cb2ee167 ON public.inventory_inventoryline USING btree (inventory_id);
CREATE INDEX IF NOT EXISTS inventory_inventoryline_product_id_48691373 ON public.inventory_inventoryline USING btree (product_id);
CREATE INDEX IF NOT EXISTS inventory_inventoryline_storage_location_id_b2290c4b ON public.inventory_inventoryline USING btree (storage_location_id);

CREATE TABLE IF NOT EXISTS inventory_stock (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    qty_available numeric(10,2) NOT NULL,
    qty_reserved numeric(10,2) NOT NULL,
    batch_no character varying(64) NOT NULL,
    expiry_date date,
    product_id bigint NOT NULL,
    storage_location_id bigint NOT NULL,
    CONSTRAINT inventory_stock_pkey PRIMARY KEY (id),
    CONSTRAINT uniq_stock_product_location_batch UNIQUE (product_id, storage_location_id, batch_no)
);

CREATE INDEX IF NOT EXISTS idx_stock_location ON public.inventory_stock USING btree (storage_location_id);
CREATE INDEX IF NOT EXISTS idx_stock_product ON public.inventory_stock USING btree (product_id);
CREATE INDEX IF NOT EXISTS idx_stock_qty_available ON public.inventory_stock USING btree (qty_available);
CREATE INDEX IF NOT EXISTS inventory_stock_product_id_b75f69ba ON public.inventory_stock USING btree (product_id);
CREATE INDEX IF NOT EXISTS inventory_stock_storage_location_id_df65ac93 ON public.inventory_stock USING btree (storage_location_id);

CREATE TABLE IF NOT EXISTS picking_order (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    number character varying(32) NOT NULL,
    customer_name character varying(255) NOT NULL,
    customer_phone character varying(32) NOT NULL,
    customer_email character varying(254) NOT NULL,
    status character varying(16) NOT NULL,
    source character varying(32) NOT NULL,
    external_id character varying(64) NOT NULL,
    confirmed_at timestamp with time zone,
    picked_at timestamp with time zone,
    shipped_at timestamp with time zone,
    reserved_at_window boolean NOT NULL,
    window_number character varying(16) NOT NULL,
    created_by_id bigint NOT NULL,
    picked_by_id bigint,
    CONSTRAINT picking_order_number_key UNIQUE (number),
    CONSTRAINT picking_order_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_order_number ON public.picking_order USING btree (number);
CREATE INDEX IF NOT EXISTS idx_order_status ON public.picking_order USING btree (status);
CREATE INDEX IF NOT EXISTS picking_order_created_by_id_5f019ae6 ON public.picking_order USING btree (created_by_id);
CREATE INDEX IF NOT EXISTS picking_order_number_9614f7c7_like ON public.picking_order USING btree (number varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS picking_order_picked_by_id_da1e93f2 ON public.picking_order USING btree (picked_by_id);
CREATE INDEX IF NOT EXISTS picking_order_status_ad592d85 ON public.picking_order USING btree (status);
CREATE INDEX IF NOT EXISTS picking_order_status_ad592d85_like ON public.picking_order USING btree (status varchar_pattern_ops);

CREATE TABLE IF NOT EXISTS picking_orderline (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    qty_ordered numeric(10,2) NOT NULL,
    qty_picked numeric(10,2) NOT NULL,
    price numeric(10,2),
    order_id bigint NOT NULL,
    product_id bigint NOT NULL,
    CONSTRAINT picking_orderline_pkey PRIMARY KEY (id),
    CONSTRAINT uniq_order_line_order_product UNIQUE (order_id, product_id)
);

CREATE INDEX IF NOT EXISTS picking_orderline_order_id_5686a0a4 ON public.picking_orderline USING btree (order_id);
CREATE INDEX IF NOT EXISTS picking_orderline_product_id_65d53bcc ON public.picking_orderline USING btree (product_id);

CREATE TABLE IF NOT EXISTS picking_pickingline (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    qty_picked numeric(10,2) NOT NULL,
    scanned_oem character varying(64) NOT NULL,
    order_line_id bigint NOT NULL,
    stock_id bigint NOT NULL,
    task_id bigint NOT NULL,
    CONSTRAINT picking_pickingline_pkey PRIMARY KEY (id),
    CONSTRAINT uniq_picking_line_task_order_stock UNIQUE (task_id, order_line_id, stock_id)
);

CREATE INDEX IF NOT EXISTS picking_pickingline_order_line_id_9a5b6164 ON public.picking_pickingline USING btree (order_line_id);
CREATE INDEX IF NOT EXISTS picking_pickingline_stock_id_d45f37de ON public.picking_pickingline USING btree (stock_id);
CREATE INDEX IF NOT EXISTS picking_pickingline_task_id_bc84814a ON public.picking_pickingline USING btree (task_id);

CREATE TABLE IF NOT EXISTS picking_pickingtask (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    status character varying(16) NOT NULL,
    zone_type_code character varying(32) NOT NULL,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    assigned_to_id bigint,
    order_id bigint NOT NULL,
    CONSTRAINT picking_pickingtask_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_picking_task_status ON public.picking_pickingtask USING btree (status);
CREATE INDEX IF NOT EXISTS idx_picking_task_zone ON public.picking_pickingtask USING btree (zone_type_code);
CREATE INDEX IF NOT EXISTS picking_pickingtask_assigned_to_id_49422106 ON public.picking_pickingtask USING btree (assigned_to_id);
CREATE INDEX IF NOT EXISTS picking_pickingtask_order_id_1f3de332 ON public.picking_pickingtask USING btree (order_id);
CREATE INDEX IF NOT EXISTS picking_pickingtask_status_f7f68131 ON public.picking_pickingtask USING btree (status);
CREATE INDEX IF NOT EXISTS picking_pickingtask_status_f7f68131_like ON public.picking_pickingtask USING btree (status varchar_pattern_ops);

CREATE TABLE IF NOT EXISTS receiving_receiving (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    number character varying(32) NOT NULL,
    supplier_name character varying(255) NOT NULL,
    supplier_doc_no character varying(64) NOT NULL,
    status character varying(16) NOT NULL,
    expected_at timestamp with time zone,
    completed_at timestamp with time zone,
    created_by_id bigint NOT NULL,
    warehouse_id bigint,
    CONSTRAINT receiving_receiving_number_key UNIQUE (number),
    CONSTRAINT receiving_receiving_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS receiving_receiving_created_by_id_af5aca15 ON public.receiving_receiving USING btree (created_by_id);
CREATE INDEX IF NOT EXISTS receiving_receiving_number_61dece7d_like ON public.receiving_receiving USING btree (number varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS receiving_receiving_status_3c04b4ee ON public.receiving_receiving USING btree (status);
CREATE INDEX IF NOT EXISTS receiving_receiving_status_3c04b4ee_like ON public.receiving_receiving USING btree (status varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS receiving_receiving_warehouse_id_e28cf161 ON public.receiving_receiving USING btree (warehouse_id);

CREATE TABLE IF NOT EXISTS receiving_receivingline (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    supplier_sku character varying(64) NOT NULL,
    qty_expected numeric(10,2) NOT NULL,
    qty_received numeric(10,2) NOT NULL,
    has_serial_numbers boolean NOT NULL,
    product_id bigint NOT NULL,
    receiving_id bigint NOT NULL,
    storage_location_id bigint,
    CONSTRAINT receiving_receivingline_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS receiving_receivingline_product_id_e58e8a4a ON public.receiving_receivingline USING btree (product_id);
CREATE INDEX IF NOT EXISTS receiving_receivingline_receiving_id_191633c2 ON public.receiving_receivingline USING btree (receiving_id);
CREATE INDEX IF NOT EXISTS receiving_receivingline_storage_location_id_2ad8ea1c ON public.receiving_receivingline USING btree (storage_location_id);

CREATE TABLE IF NOT EXISTS receiving_receivingserial (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    serial_number character varying(128) NOT NULL,
    line_id bigint NOT NULL,
    CONSTRAINT receiving_receivingserial_line_id_serial_number_76f2e14f_uniq UNIQUE (line_id, serial_number),
    CONSTRAINT receiving_receivingserial_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS receiving_receivingserial_line_id_c0f00f36 ON public.receiving_receivingserial USING btree (line_id);

CREATE TABLE IF NOT EXISTS receiving_supplier (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    code character varying(24) NOT NULL,
    name character varying(255) NOT NULL,
    is_active boolean NOT NULL,
    CONSTRAINT receiving_supplier_code_key UNIQUE (code),
    CONSTRAINT receiving_supplier_name_key UNIQUE (name),
    CONSTRAINT receiving_supplier_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS receiving_supplier_code_3840c2fb_like ON public.receiving_supplier USING btree (code varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS receiving_supplier_name_5eb53e7f_like ON public.receiving_supplier USING btree (name varchar_pattern_ops);

CREATE TABLE IF NOT EXISTS reports_abcxyzanalysis (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    period_start date NOT NULL,
    period_end date NOT NULL,
    total_sales_qty numeric(12,2) NOT NULL,
    total_sales_amount numeric(12,2) NOT NULL,
    abc_class character varying(1) NOT NULL,
    xyz_class character varying(1) NOT NULL,
    coefficient_variation numeric(10,4),
    product_id bigint NOT NULL,
    CONSTRAINT reports_abcxyzanalysis_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_abcxyz_class ON public.reports_abcxyzanalysis USING btree (abc_class, xyz_class);
CREATE INDEX IF NOT EXISTS idx_abcxyz_period ON public.reports_abcxyzanalysis USING btree (period_start, period_end);
CREATE INDEX IF NOT EXISTS reports_abcxyzanalysis_product_id_c99f6e1c ON public.reports_abcxyzanalysis USING btree (product_id);

CREATE TABLE IF NOT EXISTS reports_analogvsoriginalreport (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    period_start date NOT NULL,
    period_end date NOT NULL,
    original_sales_qty numeric(10,2) NOT NULL,
    analog_sales_qty numeric(10,2) NOT NULL,
    original_sales_amount numeric(12,2) NOT NULL,
    analog_sales_amount numeric(12,2) NOT NULL,
    substitution_rate numeric(5,2),
    calculated_at timestamp with time zone NOT NULL,
    analog_product_id bigint NOT NULL,
    original_product_id bigint NOT NULL,
    CONSTRAINT reports_analogvsoriginalreport_pkey PRIMARY KEY (id),
    CONSTRAINT uniq_analog_report_period_products UNIQUE (period_start, period_end, original_product_id, analog_product_id)
);

CREATE INDEX IF NOT EXISTS reports_analogvsoriginalreport_analog_product_id_6f2221f9 ON public.reports_analogvsoriginalreport USING btree (analog_product_id);
CREATE INDEX IF NOT EXISTS reports_analogvsoriginalreport_original_product_id_8439c830 ON public.reports_analogvsoriginalreport USING btree (original_product_id);

CREATE TABLE IF NOT EXISTS reports_deadstockreport (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    qty_available numeric(10,2) NOT NULL,
    days_without_movement integer NOT NULL,
    last_movement_date date,
    estimated_value numeric(12,2),
    calculated_at timestamp with time zone NOT NULL,
    product_id bigint NOT NULL,
    stock_id bigint,
    CONSTRAINT reports_deadstockreport_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_dead_stock_calculated ON public.reports_deadstockreport USING btree (calculated_at);
CREATE INDEX IF NOT EXISTS idx_dead_stock_days ON public.reports_deadstockreport USING btree (days_without_movement);
CREATE INDEX IF NOT EXISTS reports_deadstockreport_product_id_8689f008 ON public.reports_deadstockreport USING btree (product_id);
CREATE INDEX IF NOT EXISTS reports_deadstockreport_stock_id_762893bd ON public.reports_deadstockreport USING btree (stock_id);

CREATE TABLE IF NOT EXISTS reports_demandforecast (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    forecast_date date NOT NULL,
    period_start date NOT NULL,
    period_end date NOT NULL,
    forecasted_qty numeric(12,2) NOT NULL,
    confidence_level numeric(5,2),
    seasonal_factor numeric(5,2),
    trend_factor numeric(5,2),
    historical_sales_qty numeric(12,2),
    historical_period_start date,
    historical_period_end date,
    calculated_at timestamp with time zone NOT NULL,
    notes text NOT NULL,
    calculated_by_id bigint,
    product_id bigint NOT NULL,
    CONSTRAINT reports_demandforecast_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_forecast_period ON public.reports_demandforecast USING btree (period_start, period_end);
CREATE INDEX IF NOT EXISTS idx_forecast_product_date ON public.reports_demandforecast USING btree (product_id, forecast_date);
CREATE INDEX IF NOT EXISTS reports_demandforecast_calculated_by_id_16e831d6 ON public.reports_demandforecast USING btree (calculated_by_id);
CREATE INDEX IF NOT EXISTS reports_demandforecast_product_id_19424a9f ON public.reports_demandforecast USING btree (product_id);

CREATE TABLE IF NOT EXISTS reports_pickingerror (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    error_type character varying(32) NOT NULL,
    expected_qty numeric(10,2) NOT NULL,
    actual_qty numeric(10,2),
    detected_at timestamp with time zone NOT NULL,
    resolved boolean NOT NULL,
    resolved_at timestamp with time zone,
    notes text NOT NULL,
    actual_product_id bigint,
    detected_by_id bigint NOT NULL,
    expected_product_id bigint NOT NULL,
    order_line_id bigint NOT NULL,
    picking_line_id bigint,
    resolved_by_id bigint,
    CONSTRAINT reports_pickingerror_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_picking_error_detected ON public.reports_pickingerror USING btree (detected_at);
CREATE INDEX IF NOT EXISTS idx_picking_error_resolved ON public.reports_pickingerror USING btree (resolved);
CREATE INDEX IF NOT EXISTS idx_picking_error_type ON public.reports_pickingerror USING btree (error_type);
CREATE INDEX IF NOT EXISTS reports_pickingerror_actual_product_id_908d7987 ON public.reports_pickingerror USING btree (actual_product_id);
CREATE INDEX IF NOT EXISTS reports_pickingerror_detected_by_id_7dd65dff ON public.reports_pickingerror USING btree (detected_by_id);
CREATE INDEX IF NOT EXISTS reports_pickingerror_expected_product_id_ecd80eed ON public.reports_pickingerror USING btree (expected_product_id);
CREATE INDEX IF NOT EXISTS reports_pickingerror_order_line_id_2d06d75c ON public.reports_pickingerror USING btree (order_line_id);
CREATE INDEX IF NOT EXISTS reports_pickingerror_picking_line_id_b0c67b74 ON public.reports_pickingerror USING btree (picking_line_id);
CREATE INDEX IF NOT EXISTS reports_pickingerror_resolved_by_id_ef75f17b ON public.reports_pickingerror USING btree (resolved_by_id);

CREATE TABLE IF NOT EXISTS tasks_task (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    task_type character varying(32) NOT NULL,
    status character varying(16) NOT NULL,
    priority character varying(16) NOT NULL,
    title character varying(255) NOT NULL,
    description text NOT NULL,
    due_date timestamp with time zone,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    metadata jsonb NOT NULL,
    assigned_to_id bigint,
    created_by_id bigint NOT NULL,
    inventory_id bigint,
    order_id bigint,
    picking_task_id bigint,
    receiving_id bigint,
    CONSTRAINT tasks_task_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_task_assigned_status ON public.tasks_task USING btree (assigned_to_id, status);
CREATE INDEX IF NOT EXISTS idx_task_priority_due ON public.tasks_task USING btree (priority, due_date);
CREATE INDEX IF NOT EXISTS idx_task_type_status ON public.tasks_task USING btree (task_type, status);
CREATE INDEX IF NOT EXISTS tasks_task_assigned_to_id_e8821f61 ON public.tasks_task USING btree (assigned_to_id);
CREATE INDEX IF NOT EXISTS tasks_task_created_by_id_1345568a ON public.tasks_task USING btree (created_by_id);
CREATE INDEX IF NOT EXISTS tasks_task_inventory_id_1e18e75c ON public.tasks_task USING btree (inventory_id);
CREATE INDEX IF NOT EXISTS tasks_task_order_id_762a657b ON public.tasks_task USING btree (order_id);
CREATE INDEX IF NOT EXISTS tasks_task_picking_task_id_95b278fc ON public.tasks_task USING btree (picking_task_id);
CREATE INDEX IF NOT EXISTS tasks_task_priority_cf1cf8bf ON public.tasks_task USING btree (priority);
CREATE INDEX IF NOT EXISTS tasks_task_priority_cf1cf8bf_like ON public.tasks_task USING btree (priority varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS tasks_task_receiving_id_e6382864 ON public.tasks_task USING btree (receiving_id);
CREATE INDEX IF NOT EXISTS tasks_task_status_b001b23f ON public.tasks_task USING btree (status);
CREATE INDEX IF NOT EXISTS tasks_task_status_b001b23f_like ON public.tasks_task USING btree (status varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS tasks_task_task_type_23d4afb4 ON public.tasks_task USING btree (task_type);
CREATE INDEX IF NOT EXISTS tasks_task_task_type_23d4afb4_like ON public.tasks_task USING btree (task_type varchar_pattern_ops);

CREATE TABLE IF NOT EXISTS tasks_taskcomment (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    text text NOT NULL,
    author_id bigint NOT NULL,
    task_id bigint NOT NULL,
    CONSTRAINT tasks_taskcomment_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS tasks_taskcomment_author_id_74ce12bd ON public.tasks_taskcomment USING btree (author_id);
CREATE INDEX IF NOT EXISTS tasks_taskcomment_task_id_36403ad8 ON public.tasks_taskcomment USING btree (task_id);

CREATE TABLE IF NOT EXISTS warehouse_3d_storageobject (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    object_type character varying(16) NOT NULL,
    code character varying(64) NOT NULL,
    name character varying(255) NOT NULL,
    position_x double precision NOT NULL,
    position_z double precision NOT NULL,
    position_y double precision NOT NULL,
    width double precision NOT NULL,
    depth double precision NOT NULL,
    height double precision NOT NULL,
    rotation_y double precision NOT NULL,
    is_active boolean NOT NULL,
    warehouse_id bigint NOT NULL,
    storage_location_id bigint,
    CONSTRAINT warehouse_3d_storageobject_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_storage_obj_wh_type ON public.warehouse_3d_storageobject USING btree (warehouse_id, object_type);
CREATE INDEX IF NOT EXISTS warehouse_3d_storageobject_object_type_8597ab61 ON public.warehouse_3d_storageobject USING btree (object_type);
CREATE INDEX IF NOT EXISTS warehouse_3d_storageobject_object_type_8597ab61_like ON public.warehouse_3d_storageobject USING btree (object_type varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS warehouse_3d_storageobject_storage_location_id_3885da9d ON public.warehouse_3d_storageobject USING btree (storage_location_id);
CREATE INDEX IF NOT EXISTS warehouse_3d_storageobject_warehouse_id_a6d02078 ON public.warehouse_3d_storageobject USING btree (warehouse_id);

CREATE TABLE IF NOT EXISTS warehouse_3d_warehouselayout (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    floor_points jsonb NOT NULL,
    is_layout_defined boolean NOT NULL,
    warehouse_id bigint NOT NULL,
    CONSTRAINT warehouse_3d_warehouselayout_pkey PRIMARY KEY (id),
    CONSTRAINT warehouse_3d_warehouselayout_warehouse_id_key UNIQUE (warehouse_id)
);


DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'accounts_user_branches_branch_id_e134a618_fk_catalog_branch_id'
          AND conrelid = 'accounts_user_branches'::regclass
    ) THEN
        ALTER TABLE accounts_user_branches ADD CONSTRAINT accounts_user_branches_branch_id_e134a618_fk_catalog_branch_id FOREIGN KEY (branch_id) REFERENCES catalog_branch(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'accounts_user_branches_user_id_e71cebef_fk_accounts_user_id'
          AND conrelid = 'accounts_user_branches'::regclass
    ) THEN
        ALTER TABLE accounts_user_branches ADD CONSTRAINT accounts_user_branches_user_id_e71cebef_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES accounts_user(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'accounts_user_groups_group_id_bd11a704_fk_auth_group_id'
          AND conrelid = 'accounts_user_groups'::regclass
    ) THEN
        ALTER TABLE accounts_user_groups ADD CONSTRAINT accounts_user_groups_group_id_bd11a704_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES auth_group(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'accounts_user_groups_user_id_52b62117_fk_accounts_user_id'
          AND conrelid = 'accounts_user_groups'::regclass
    ) THEN
        ALTER TABLE accounts_user_groups ADD CONSTRAINT accounts_user_groups_user_id_52b62117_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES accounts_user(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'accounts_user_user_p_permission_id_113bb443_fk_auth_perm'
          AND conrelid = 'accounts_user_user_permissions'::regclass
    ) THEN
        ALTER TABLE accounts_user_user_permissions ADD CONSTRAINT accounts_user_user_p_permission_id_113bb443_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES auth_permission(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'accounts_user_user_p_user_id_e4f0a161_fk_accounts_'
          AND conrelid = 'accounts_user_user_permissions'::regclass
    ) THEN
        ALTER TABLE accounts_user_user_permissions ADD CONSTRAINT accounts_user_user_p_user_id_e4f0a161_fk_accounts_ FOREIGN KEY (user_id) REFERENCES accounts_user(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'api_apitoken_user_id_9cffaf33_fk_accounts_user_id'
          AND conrelid = 'api_apitoken'::regclass
    ) THEN
        ALTER TABLE api_apitoken ADD CONSTRAINT api_apitoken_user_id_9cffaf33_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES accounts_user(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'auth_group_permissio_permission_id_84c5c92e_fk_auth_perm'
          AND conrelid = 'auth_group_permissions'::regclass
    ) THEN
        ALTER TABLE auth_group_permissions ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES auth_permission(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'auth_group_permissions_group_id_b120cbf9_fk_auth_group_id'
          AND conrelid = 'auth_group_permissions'::regclass
    ) THEN
        ALTER TABLE auth_group_permissions ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES auth_group(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'auth_permission_content_type_id_2f476e4b_fk_django_co'
          AND conrelid = 'auth_permission'::regclass
    ) THEN
        ALTER TABLE auth_permission ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES django_content_type(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'catalog_backorder_created_by_id_de961824_fk_accounts_user_id'
          AND conrelid = 'catalog_backorder'::regclass
    ) THEN
        ALTER TABLE catalog_backorder ADD CONSTRAINT catalog_backorder_created_by_id_de961824_fk_accounts_user_id FOREIGN KEY (created_by_id) REFERENCES accounts_user(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'catalog_backorder_order_id_e77969b3_fk_picking_order_id'
          AND conrelid = 'catalog_backorder'::regclass
    ) THEN
        ALTER TABLE catalog_backorder ADD CONSTRAINT catalog_backorder_order_id_e77969b3_fk_picking_order_id FOREIGN KEY (order_id) REFERENCES picking_order(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'catalog_backorder_product_id_0651fc0b_fk_catalog_product_id'
          AND conrelid = 'catalog_backorder'::regclass
    ) THEN
        ALTER TABLE catalog_backorder ADD CONSTRAINT catalog_backorder_product_id_0651fc0b_fk_catalog_product_id FOREIGN KEY (product_id) REFERENCES catalog_product(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'catalog_category_parent_id_f61bd017_fk_catalog_category_id'
          AND conrelid = 'catalog_category'::regclass
    ) THEN
        ALTER TABLE catalog_category ADD CONSTRAINT catalog_category_parent_id_f61bd017_fk_catalog_category_id FOREIGN KEY (parent_id) REFERENCES catalog_category(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'catalog_product_brand_id_bb0c7890_fk_catalog_brand_id'
          AND conrelid = 'catalog_product'::regclass
    ) THEN
        ALTER TABLE catalog_product ADD CONSTRAINT catalog_product_brand_id_bb0c7890_fk_catalog_brand_id FOREIGN KEY (brand_id) REFERENCES catalog_brand(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'catalog_product_category_id_35bf920b_fk_catalog_category_id'
          AND conrelid = 'catalog_product'::regclass
    ) THEN
        ALTER TABLE catalog_product ADD CONSTRAINT catalog_product_category_id_35bf920b_fk_catalog_category_id FOREIGN KEY (category_id) REFERENCES catalog_category(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'catalog_productappli_product_id_904e4c0a_fk_catalog_p'
          AND conrelid = 'catalog_productapplicability'::regclass
    ) THEN
        ALTER TABLE catalog_productapplicability ADD CONSTRAINT catalog_productappli_product_id_904e4c0a_fk_catalog_p FOREIGN KEY (product_id) REFERENCES catalog_product(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'catalog_productappli_vehicle_model_id_3508c865_fk_catalog_v'
          AND conrelid = 'catalog_productapplicability'::regclass
    ) THEN
        ALTER TABLE catalog_productapplicability ADD CONSTRAINT catalog_productappli_vehicle_model_id_3508c865_fk_catalog_v FOREIGN KEY (vehicle_model_id) REFERENCES catalog_vehiclemodel(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'catalog_productchang_changed_by_id_80a96c42_fk_accounts_'
          AND conrelid = 'catalog_productchangelog'::regclass
    ) THEN
        ALTER TABLE catalog_productchangelog ADD CONSTRAINT catalog_productchang_changed_by_id_80a96c42_fk_accounts_ FOREIGN KEY (changed_by_id) REFERENCES accounts_user(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'catalog_productchang_product_id_d1bf08a9_fk_catalog_p'
          AND conrelid = 'catalog_productchangelog'::regclass
    ) THEN
        ALTER TABLE catalog_productchangelog ADD CONSTRAINT catalog_productchang_product_id_d1bf08a9_fk_catalog_p FOREIGN KEY (product_id) REFERENCES catalog_product(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'catalog_productcross_from_product_id_aac20dd5_fk_catalog_p'
          AND conrelid = 'catalog_productcrossreference'::regclass
    ) THEN
        ALTER TABLE catalog_productcrossreference ADD CONSTRAINT catalog_productcross_from_product_id_aac20dd5_fk_catalog_p FOREIGN KEY (from_product_id) REFERENCES catalog_product(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'catalog_productcross_to_product_id_7622d235_fk_catalog_p'
          AND conrelid = 'catalog_productcrossreference'::regclass
    ) THEN
        ALTER TABLE catalog_productcrossreference ADD CONSTRAINT catalog_productcross_to_product_id_7622d235_fk_catalog_p FOREIGN KEY (to_product_id) REFERENCES catalog_product(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'catalog_storagelocat_zone_id_2fb24172_fk_catalog_s'
          AND conrelid = 'catalog_storagelocation'::regclass
    ) THEN
        ALTER TABLE catalog_storagelocation ADD CONSTRAINT catalog_storagelocat_zone_id_2fb24172_fk_catalog_s FOREIGN KEY (zone_id) REFERENCES catalog_storagezone(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'catalog_storagezone_warehouse_id_685b5c9b_fk_catalog_w'
          AND conrelid = 'catalog_storagezone'::regclass
    ) THEN
        ALTER TABLE catalog_storagezone ADD CONSTRAINT catalog_storagezone_warehouse_id_685b5c9b_fk_catalog_w FOREIGN KEY (warehouse_id) REFERENCES catalog_warehouse(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'catalog_storagezone_zone_type_id_a4eb2043_fk_catalog_s'
          AND conrelid = 'catalog_storagezone'::regclass
    ) THEN
        ALTER TABLE catalog_storagezone ADD CONSTRAINT catalog_storagezone_zone_type_id_a4eb2043_fk_catalog_s FOREIGN KEY (zone_type_id) REFERENCES catalog_storagezonetype(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'catalog_tool_current_user_id_4aab9a88_fk_accounts_user_id'
          AND conrelid = 'catalog_tool'::regclass
    ) THEN
        ALTER TABLE catalog_tool ADD CONSTRAINT catalog_tool_current_user_id_4aab9a88_fk_accounts_user_id FOREIGN KEY (current_user_id) REFERENCES accounts_user(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'catalog_tool_warehouse_id_225ed9dc_fk_catalog_warehouse_id'
          AND conrelid = 'catalog_tool'::regclass
    ) THEN
        ALTER TABLE catalog_tool ADD CONSTRAINT catalog_tool_warehouse_id_225ed9dc_fk_catalog_warehouse_id FOREIGN KEY (warehouse_id) REFERENCES catalog_warehouse(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'catalog_vehiclemodel_make_id_15410b4c_fk_catalog_vehiclemake_id'
          AND conrelid = 'catalog_vehiclemodel'::regclass
    ) THEN
        ALTER TABLE catalog_vehiclemodel ADD CONSTRAINT catalog_vehiclemodel_make_id_15410b4c_fk_catalog_vehiclemake_id FOREIGN KEY (make_id) REFERENCES catalog_vehiclemake(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'catalog_warehouse_branch_id_f77b3dbb_fk_catalog_branch_id'
          AND conrelid = 'catalog_warehouse'::regclass
    ) THEN
        ALTER TABLE catalog_warehouse ADD CONSTRAINT catalog_warehouse_branch_id_f77b3dbb_fk_catalog_branch_id FOREIGN KEY (branch_id) REFERENCES catalog_branch(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'catalog_warehouseacc_warehouse_id_9966fc4b_fk_catalog_w'
          AND conrelid = 'catalog_warehouseaccess'::regclass
    ) THEN
        ALTER TABLE catalog_warehouseaccess ADD CONSTRAINT catalog_warehouseacc_warehouse_id_9966fc4b_fk_catalog_w FOREIGN KEY (warehouse_id) REFERENCES catalog_warehouse(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'catalog_warehouseaccess_user_id_06bf8444_fk_accounts_user_id'
          AND conrelid = 'catalog_warehouseaccess'::regclass
    ) THEN
        ALTER TABLE catalog_warehouseaccess ADD CONSTRAINT catalog_warehouseaccess_user_id_06bf8444_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES accounts_user(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'django_admin_log_content_type_id_c4bce8eb_fk_django_co'
          AND conrelid = 'django_admin_log'::regclass
    ) THEN
        ALTER TABLE django_admin_log ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES django_content_type(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'django_admin_log_user_id_c564eba6_fk_accounts_user_id'
          AND conrelid = 'django_admin_log'::regclass
    ) THEN
        ALTER TABLE django_admin_log ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES accounts_user(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'inventory_inventory_created_by_id_6b45551c_fk_accounts_user_id'
          AND conrelid = 'inventory_inventory'::regclass
    ) THEN
        ALTER TABLE inventory_inventory ADD CONSTRAINT inventory_inventory_created_by_id_6b45551c_fk_accounts_user_id FOREIGN KEY (created_by_id) REFERENCES accounts_user(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'inventory_inventory_zone_id_f9ac22ee_fk_catalog_storagezone_id'
          AND conrelid = 'inventory_inventory'::regclass
    ) THEN
        ALTER TABLE inventory_inventory ADD CONSTRAINT inventory_inventory_zone_id_f9ac22ee_fk_catalog_storagezone_id FOREIGN KEY (zone_id) REFERENCES catalog_storagezone(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'inventory_inventoryl_inventory_id_cb2ee167_fk_inventory'
          AND conrelid = 'inventory_inventoryline'::regclass
    ) THEN
        ALTER TABLE inventory_inventoryline ADD CONSTRAINT inventory_inventoryl_inventory_id_cb2ee167_fk_inventory FOREIGN KEY (inventory_id) REFERENCES inventory_inventory(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'inventory_inventoryl_product_id_48691373_fk_catalog_p'
          AND conrelid = 'inventory_inventoryline'::regclass
    ) THEN
        ALTER TABLE inventory_inventoryline ADD CONSTRAINT inventory_inventoryl_product_id_48691373_fk_catalog_p FOREIGN KEY (product_id) REFERENCES catalog_product(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'inventory_inventoryl_storage_location_id_b2290c4b_fk_catalog_s'
          AND conrelid = 'inventory_inventoryline'::regclass
    ) THEN
        ALTER TABLE inventory_inventoryline ADD CONSTRAINT inventory_inventoryl_storage_location_id_b2290c4b_fk_catalog_s FOREIGN KEY (storage_location_id) REFERENCES catalog_storagelocation(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'inventory_stock_product_id_b75f69ba_fk_catalog_product_id'
          AND conrelid = 'inventory_stock'::regclass
    ) THEN
        ALTER TABLE inventory_stock ADD CONSTRAINT inventory_stock_product_id_b75f69ba_fk_catalog_product_id FOREIGN KEY (product_id) REFERENCES catalog_product(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'inventory_stock_storage_location_id_df65ac93_fk_catalog_s'
          AND conrelid = 'inventory_stock'::regclass
    ) THEN
        ALTER TABLE inventory_stock ADD CONSTRAINT inventory_stock_storage_location_id_df65ac93_fk_catalog_s FOREIGN KEY (storage_location_id) REFERENCES catalog_storagelocation(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'picking_order_created_by_id_5f019ae6_fk_accounts_user_id'
          AND conrelid = 'picking_order'::regclass
    ) THEN
        ALTER TABLE picking_order ADD CONSTRAINT picking_order_created_by_id_5f019ae6_fk_accounts_user_id FOREIGN KEY (created_by_id) REFERENCES accounts_user(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'picking_order_picked_by_id_da1e93f2_fk_accounts_user_id'
          AND conrelid = 'picking_order'::regclass
    ) THEN
        ALTER TABLE picking_order ADD CONSTRAINT picking_order_picked_by_id_da1e93f2_fk_accounts_user_id FOREIGN KEY (picked_by_id) REFERENCES accounts_user(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'picking_orderline_order_id_5686a0a4_fk_picking_order_id'
          AND conrelid = 'picking_orderline'::regclass
    ) THEN
        ALTER TABLE picking_orderline ADD CONSTRAINT picking_orderline_order_id_5686a0a4_fk_picking_order_id FOREIGN KEY (order_id) REFERENCES picking_order(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'picking_orderline_product_id_65d53bcc_fk_catalog_product_id'
          AND conrelid = 'picking_orderline'::regclass
    ) THEN
        ALTER TABLE picking_orderline ADD CONSTRAINT picking_orderline_product_id_65d53bcc_fk_catalog_product_id FOREIGN KEY (product_id) REFERENCES catalog_product(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'picking_pickingline_order_line_id_9a5b6164_fk_picking_o'
          AND conrelid = 'picking_pickingline'::regclass
    ) THEN
        ALTER TABLE picking_pickingline ADD CONSTRAINT picking_pickingline_order_line_id_9a5b6164_fk_picking_o FOREIGN KEY (order_line_id) REFERENCES picking_orderline(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'picking_pickingline_stock_id_d45f37de_fk_inventory_stock_id'
          AND conrelid = 'picking_pickingline'::regclass
    ) THEN
        ALTER TABLE picking_pickingline ADD CONSTRAINT picking_pickingline_stock_id_d45f37de_fk_inventory_stock_id FOREIGN KEY (stock_id) REFERENCES inventory_stock(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'picking_pickingline_task_id_bc84814a_fk_picking_pickingtask_id'
          AND conrelid = 'picking_pickingline'::regclass
    ) THEN
        ALTER TABLE picking_pickingline ADD CONSTRAINT picking_pickingline_task_id_bc84814a_fk_picking_pickingtask_id FOREIGN KEY (task_id) REFERENCES picking_pickingtask(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'picking_pickingtask_assigned_to_id_49422106_fk_accounts_user_id'
          AND conrelid = 'picking_pickingtask'::regclass
    ) THEN
        ALTER TABLE picking_pickingtask ADD CONSTRAINT picking_pickingtask_assigned_to_id_49422106_fk_accounts_user_id FOREIGN KEY (assigned_to_id) REFERENCES accounts_user(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'picking_pickingtask_order_id_1f3de332_fk_picking_order_id'
          AND conrelid = 'picking_pickingtask'::regclass
    ) THEN
        ALTER TABLE picking_pickingtask ADD CONSTRAINT picking_pickingtask_order_id_1f3de332_fk_picking_order_id FOREIGN KEY (order_id) REFERENCES picking_order(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'receiving_receiving_created_by_id_af5aca15_fk_accounts_user_id'
          AND conrelid = 'receiving_receiving'::regclass
    ) THEN
        ALTER TABLE receiving_receiving ADD CONSTRAINT receiving_receiving_created_by_id_af5aca15_fk_accounts_user_id FOREIGN KEY (created_by_id) REFERENCES accounts_user(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'receiving_receiving_warehouse_id_e28cf161_fk_catalog_w'
          AND conrelid = 'receiving_receiving'::regclass
    ) THEN
        ALTER TABLE receiving_receiving ADD CONSTRAINT receiving_receiving_warehouse_id_e28cf161_fk_catalog_w FOREIGN KEY (warehouse_id) REFERENCES catalog_warehouse(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'receiving_receivingl_product_id_e58e8a4a_fk_catalog_p'
          AND conrelid = 'receiving_receivingline'::regclass
    ) THEN
        ALTER TABLE receiving_receivingline ADD CONSTRAINT receiving_receivingl_product_id_e58e8a4a_fk_catalog_p FOREIGN KEY (product_id) REFERENCES catalog_product(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'receiving_receivingl_receiving_id_191633c2_fk_receiving'
          AND conrelid = 'receiving_receivingline'::regclass
    ) THEN
        ALTER TABLE receiving_receivingline ADD CONSTRAINT receiving_receivingl_receiving_id_191633c2_fk_receiving FOREIGN KEY (receiving_id) REFERENCES receiving_receiving(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'receiving_receivingl_storage_location_id_2ad8ea1c_fk_catalog_s'
          AND conrelid = 'receiving_receivingline'::regclass
    ) THEN
        ALTER TABLE receiving_receivingline ADD CONSTRAINT receiving_receivingl_storage_location_id_2ad8ea1c_fk_catalog_s FOREIGN KEY (storage_location_id) REFERENCES catalog_storagelocation(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'receiving_receivings_line_id_c0f00f36_fk_receiving'
          AND conrelid = 'receiving_receivingserial'::regclass
    ) THEN
        ALTER TABLE receiving_receivingserial ADD CONSTRAINT receiving_receivings_line_id_c0f00f36_fk_receiving FOREIGN KEY (line_id) REFERENCES receiving_receivingline(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'reports_abcxyzanalys_product_id_c99f6e1c_fk_catalog_p'
          AND conrelid = 'reports_abcxyzanalysis'::regclass
    ) THEN
        ALTER TABLE reports_abcxyzanalysis ADD CONSTRAINT reports_abcxyzanalys_product_id_c99f6e1c_fk_catalog_p FOREIGN KEY (product_id) REFERENCES catalog_product(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'reports_analogvsorig_analog_product_id_6f2221f9_fk_catalog_p'
          AND conrelid = 'reports_analogvsoriginalreport'::regclass
    ) THEN
        ALTER TABLE reports_analogvsoriginalreport ADD CONSTRAINT reports_analogvsorig_analog_product_id_6f2221f9_fk_catalog_p FOREIGN KEY (analog_product_id) REFERENCES catalog_product(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'reports_analogvsorig_original_product_id_8439c830_fk_catalog_p'
          AND conrelid = 'reports_analogvsoriginalreport'::regclass
    ) THEN
        ALTER TABLE reports_analogvsoriginalreport ADD CONSTRAINT reports_analogvsorig_original_product_id_8439c830_fk_catalog_p FOREIGN KEY (original_product_id) REFERENCES catalog_product(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'reports_deadstockrep_product_id_8689f008_fk_catalog_p'
          AND conrelid = 'reports_deadstockreport'::regclass
    ) THEN
        ALTER TABLE reports_deadstockreport ADD CONSTRAINT reports_deadstockrep_product_id_8689f008_fk_catalog_p FOREIGN KEY (product_id) REFERENCES catalog_product(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'reports_deadstockreport_stock_id_762893bd_fk_inventory_stock_id'
          AND conrelid = 'reports_deadstockreport'::regclass
    ) THEN
        ALTER TABLE reports_deadstockreport ADD CONSTRAINT reports_deadstockreport_stock_id_762893bd_fk_inventory_stock_id FOREIGN KEY (stock_id) REFERENCES inventory_stock(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'reports_demandforeca_calculated_by_id_16e831d6_fk_accounts_'
          AND conrelid = 'reports_demandforecast'::regclass
    ) THEN
        ALTER TABLE reports_demandforecast ADD CONSTRAINT reports_demandforeca_calculated_by_id_16e831d6_fk_accounts_ FOREIGN KEY (calculated_by_id) REFERENCES accounts_user(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'reports_demandforeca_product_id_19424a9f_fk_catalog_p'
          AND conrelid = 'reports_demandforecast'::regclass
    ) THEN
        ALTER TABLE reports_demandforecast ADD CONSTRAINT reports_demandforeca_product_id_19424a9f_fk_catalog_p FOREIGN KEY (product_id) REFERENCES catalog_product(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'reports_pickingerror_actual_product_id_908d7987_fk_catalog_p'
          AND conrelid = 'reports_pickingerror'::regclass
    ) THEN
        ALTER TABLE reports_pickingerror ADD CONSTRAINT reports_pickingerror_actual_product_id_908d7987_fk_catalog_p FOREIGN KEY (actual_product_id) REFERENCES catalog_product(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'reports_pickingerror_detected_by_id_7dd65dff_fk_accounts_'
          AND conrelid = 'reports_pickingerror'::regclass
    ) THEN
        ALTER TABLE reports_pickingerror ADD CONSTRAINT reports_pickingerror_detected_by_id_7dd65dff_fk_accounts_ FOREIGN KEY (detected_by_id) REFERENCES accounts_user(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'reports_pickingerror_expected_product_id_ecd80eed_fk_catalog_p'
          AND conrelid = 'reports_pickingerror'::regclass
    ) THEN
        ALTER TABLE reports_pickingerror ADD CONSTRAINT reports_pickingerror_expected_product_id_ecd80eed_fk_catalog_p FOREIGN KEY (expected_product_id) REFERENCES catalog_product(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'reports_pickingerror_order_line_id_2d06d75c_fk_picking_o'
          AND conrelid = 'reports_pickingerror'::regclass
    ) THEN
        ALTER TABLE reports_pickingerror ADD CONSTRAINT reports_pickingerror_order_line_id_2d06d75c_fk_picking_o FOREIGN KEY (order_line_id) REFERENCES picking_orderline(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'reports_pickingerror_picking_line_id_b0c67b74_fk_picking_p'
          AND conrelid = 'reports_pickingerror'::regclass
    ) THEN
        ALTER TABLE reports_pickingerror ADD CONSTRAINT reports_pickingerror_picking_line_id_b0c67b74_fk_picking_p FOREIGN KEY (picking_line_id) REFERENCES picking_pickingline(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'reports_pickingerror_resolved_by_id_ef75f17b_fk_accounts_'
          AND conrelid = 'reports_pickingerror'::regclass
    ) THEN
        ALTER TABLE reports_pickingerror ADD CONSTRAINT reports_pickingerror_resolved_by_id_ef75f17b_fk_accounts_ FOREIGN KEY (resolved_by_id) REFERENCES accounts_user(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'tasks_task_assigned_to_id_e8821f61_fk_accounts_user_id'
          AND conrelid = 'tasks_task'::regclass
    ) THEN
        ALTER TABLE tasks_task ADD CONSTRAINT tasks_task_assigned_to_id_e8821f61_fk_accounts_user_id FOREIGN KEY (assigned_to_id) REFERENCES accounts_user(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'tasks_task_created_by_id_1345568a_fk_accounts_user_id'
          AND conrelid = 'tasks_task'::regclass
    ) THEN
        ALTER TABLE tasks_task ADD CONSTRAINT tasks_task_created_by_id_1345568a_fk_accounts_user_id FOREIGN KEY (created_by_id) REFERENCES accounts_user(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'tasks_task_inventory_id_1e18e75c_fk_inventory_inventory_id'
          AND conrelid = 'tasks_task'::regclass
    ) THEN
        ALTER TABLE tasks_task ADD CONSTRAINT tasks_task_inventory_id_1e18e75c_fk_inventory_inventory_id FOREIGN KEY (inventory_id) REFERENCES inventory_inventory(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'tasks_task_order_id_762a657b_fk_picking_order_id'
          AND conrelid = 'tasks_task'::regclass
    ) THEN
        ALTER TABLE tasks_task ADD CONSTRAINT tasks_task_order_id_762a657b_fk_picking_order_id FOREIGN KEY (order_id) REFERENCES picking_order(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'tasks_task_picking_task_id_95b278fc_fk_picking_pickingtask_id'
          AND conrelid = 'tasks_task'::regclass
    ) THEN
        ALTER TABLE tasks_task ADD CONSTRAINT tasks_task_picking_task_id_95b278fc_fk_picking_pickingtask_id FOREIGN KEY (picking_task_id) REFERENCES picking_pickingtask(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'tasks_task_receiving_id_e6382864_fk_receiving_receiving_id'
          AND conrelid = 'tasks_task'::regclass
    ) THEN
        ALTER TABLE tasks_task ADD CONSTRAINT tasks_task_receiving_id_e6382864_fk_receiving_receiving_id FOREIGN KEY (receiving_id) REFERENCES receiving_receiving(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'tasks_taskcomment_author_id_74ce12bd_fk_accounts_user_id'
          AND conrelid = 'tasks_taskcomment'::regclass
    ) THEN
        ALTER TABLE tasks_taskcomment ADD CONSTRAINT tasks_taskcomment_author_id_74ce12bd_fk_accounts_user_id FOREIGN KEY (author_id) REFERENCES accounts_user(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'tasks_taskcomment_task_id_36403ad8_fk_tasks_task_id'
          AND conrelid = 'tasks_taskcomment'::regclass
    ) THEN
        ALTER TABLE tasks_taskcomment ADD CONSTRAINT tasks_taskcomment_task_id_36403ad8_fk_tasks_task_id FOREIGN KEY (task_id) REFERENCES tasks_task(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'warehouse_3d_storage_storage_location_id_3885da9d_fk_catalog_s'
          AND conrelid = 'warehouse_3d_storageobject'::regclass
    ) THEN
        ALTER TABLE warehouse_3d_storageobject ADD CONSTRAINT warehouse_3d_storage_storage_location_id_3885da9d_fk_catalog_s FOREIGN KEY (storage_location_id) REFERENCES catalog_storagelocation(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'warehouse_3d_storage_warehouse_id_a6d02078_fk_catalog_w'
          AND conrelid = 'warehouse_3d_storageobject'::regclass
    ) THEN
        ALTER TABLE warehouse_3d_storageobject ADD CONSTRAINT warehouse_3d_storage_warehouse_id_a6d02078_fk_catalog_w FOREIGN KEY (warehouse_id) REFERENCES catalog_warehouse(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'warehouse_3d_warehou_warehouse_id_69e00f50_fk_catalog_w'
          AND conrelid = 'warehouse_3d_warehouselayout'::regclass
    ) THEN
        ALTER TABLE warehouse_3d_warehouselayout ADD CONSTRAINT warehouse_3d_warehou_warehouse_id_69e00f50_fk_catalog_w FOREIGN KEY (warehouse_id) REFERENCES catalog_warehouse(id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

COMMIT;
