# Generated by Django 5.2.10 on 2026-04-28 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("INFO", "Информация"),
                            ("SUCCESS", "Успех"),
                            ("WARNING", "Предупреждение"),
                            ("DANGER", "Ошибка"),
                        ],
                        db_index=True,
                        default="INFO",
                        max_length=16,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Низкий"),
                            ("NORMAL", "Обычный"),
                            ("HIGH", "Высокий"),
                        ],
                        db_index=True,
                        default="NORMAL",
                        max_length=8,
                        verbose_name="Приоритет",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                ("body", models.TextField(blank=True, verbose_name="Текст")),
                (
                    "link",
                    models.CharField(blank=True, max_length=500, verbose_name="Ссылка"),
                ),
                (
                    "dedup_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=128,
                        verbose_name="Ключ дедупликации",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Прочитано"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Прочитано в"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Создано"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Уведомление",
                "verbose_name_plural": "Уведомления",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read", "-created_at"],
                        name="idx_notif_user_unread",
                    )
                ],
            },
        ),
    ]
